### ISSUE TITLE
middleware error in Nextjs@15 : TypeError: _react.default.createContext is not a function

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [nextauthjs/next-auth#11033]
### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
    Memory: 18.71 GB / 31.94 GB
  Binaries:
    Node: 19.0.0 - ~\.version-fox\cache\nodejs\current\node.EXE
    npm: 8.19.2 - ~\.version-fox\cache\nodejs\current\npm.CMD
    pnpm: 9.1.3 - ~\.version-fox\cache\nodejs\current\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.67)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    next: 15.0.0-rc.0 => 15.0.0-rc.0
    next-auth: 5.0.0-beta.18 => 5.0.0-beta.18
    react: 19.0.0-rc-f994737d14-20240522 => 19.0.0-rc-f994737d14-20240522
```

### Reproduction URL

https://github.com/liuhuapiaoyuan/lesson-nextjs-nextauth

### Describe the issue

![image](https://github.com/nextauthjs/next-auth/assets/8020726/09e7efbd-80af-44c6-8d7c-11fb6bf28311)

### How to reproduce

middleware.ts

```
export { auth as middleware } from "@/auth";


```

### Expected behavior

Be able to use middleware correctly!

**Comment by liuhuapiaoyuan** [comment]
https://github.com/vercel/next.js/issues/66162
I found the same issue

**Comment by liuhuapiaoyuan** [comment]
Next@15.0.0-canary.1

This has been resolved

**Comment by saurabhsri108** [comment]
> Next@15.0.0-canary.1
> 
> This has been resolved

It's not resolved. Checked now.

**Comment by l0gicgate** [comment]
It is not resolved @liuhuapiaoyuan the fix did not make it into the Next 15 @ Canary branch, it's only on the Next 14 @ Canary branch.

I'm running Next@15.0.0-canary.6 and it's still not working.

**Comment by liuhuapiaoyuan** [comment]
You can send us your code for us to take a look

@l0gicgate

**Comment by l0gicgate** [comment]
@liuhuapiaoyuan the fix landed for this in this release of Next 14:
https://github.com/vercel/next.js/releases/tag/v14.3.0-canary.81

This PR specifically:
https://github.com/vercel/next.js/pull/66175

It is not in any of the Next 15 Canary releases.

I have asked for it to be ported to the Next 15 canary branch:
https://github.com/vercel/next.js/pull/66175#issuecomment-2144014259

**Comment by ahmad-safar** [comment]
I have the same issue because I use `next dev --turbo`. Disabling Turbopack will fix the issue.
Just run `next dev`.

**Comment by l0gicgate** [comment]
@ahmad-safar that's not a solution, `next dev` is painfully slow. This should work with turbopack.

**Comment by tom-sherman** [comment]
Same issue here on next `15.0.0-canary.25`, only errors with `next dev --turbo`. Can we re-open this?

I have a smaller reproduction here on the latest canary:

https://github.com/tom-sherman/next-15-next-auth-middleware-error

**Comment by nguyentrungson97** [comment]
Same here. `--turbo` is the cause of this

**Comment by balazsorban44** [comment]
Please don't comment on closed issued, they aren't monitored. Open a new one with a reproduction, thanks! :pray:

FWIW, I tried https://github.com/nextauthjs/next-auth/issues/11033#issuecomment-2161356267 and could not reproduce the issue.
