### ISSUE TITLE
@auth/prisma-adapter@2.9.0 does not work with prisma/client@6.6.0

### ISSUE THREAD

**Issue by zntb** [nextauthjs/next-auth#12899]
### Adapter type

@auth/prisma-adapter

### Environment

 System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 3.13 GB / 15.94 GB
  Binaries:
    Node: 22.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.6.2 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.2.5 - ~\.bun\bin\bun.EXE
  Browsers:
    Chrome: 135.0.7049.115
    Edge: Chromium (134.0.3124.93)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @auth/prisma-adapter: ^2.9.0 => 2.9.0
    next: 15.3.1 => 15.3.1
    next-auth: ^5.0.0-beta.26 => 5.0.0-beta.26
    react: ^19.0.0 => 19.1.0

### Reproduction URL

https://github.com/zntb/authjs-prisma-bug

### Describe the issue

This error appears during build:

```bash
> authjs-prisma-bug@0.1.0 build
> next build

   ▲ Next.js 15.3.1
   - Environments: .env

   Creating an optimized production build ...
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (196kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
Failed to compile.

node:child_process
Module build failed: UnhandledSchemeError: Reading from "node:child_process" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408376
    at Hook.eval [as callAsync] (eval at create (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:14:9224), <anonymous>:6:1)
    at Object.processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408301)
    at processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)
    at runLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408163)
    at NormalModule.build (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:410176)
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:82494
    at NormalModule.needBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:414126)

Import trace for requested module:
node:child_process
./node_modules/@prisma/client/runtime/library.mjs
./node_modules/@auth/prisma-adapter/index.js
./auth.ts

node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408376
    at Hook.eval [as callAsync] (eval at create (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:14:9224), <anonymous>:6:1)
    at Object.processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408301)
    at processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)
    at runLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408163)
    at NormalModule.build (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:410176)
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:82494
    at NormalModule.needBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:414126)

Import trace for requested module:
node:fs/promises
./node_modules/@prisma/client/runtime/library.mjs
./node_modules/@auth/prisma-adapter/index.js
./auth.ts

node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408376
    at Hook.eval [as callAsync] (eval at create (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:14:9224), <anonymous>:6:1)
    at Object.processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408301)
    at processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)
    at runLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408163)
    at NormalModule.build (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:410176)
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:82494
    at NormalModule.needBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:414126)

Import trace for requested module:
node:fs
./node_modules/@prisma/client/runtime/library.mjs
./node_modules/@auth/prisma-adapter/index.js
./auth.ts

node:module
Module build failed: UnhandledSchemeError: Reading from "node:module" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408376
    at Hook.eval [as callAsync] (eval at create (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:14:9224), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:14:6378)
    at Object.processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408301)
    at processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)
    at runLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408163)
    at NormalModule.build (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:410176)
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:82494

Import trace for requested module:
node:module
./node_modules/@prisma/client/runtime/library.mjs
./node_modules/@auth/prisma-adapter/index.js
./auth.ts

node:os
Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408376
    at Hook.eval [as callAsync] (eval at create (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:14:9224), <anonymous>:6:1)
    at Object.processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408301)
    at processResource (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)
    at runLoaders (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:408163)
    at NormalModule.build (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:410176)
    at E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:82494
    at NormalModule.needBuild (E:\PROJECTS\NEXTJS\authjs-prisma-bug\node_modules\next\dist\compiled\webpack\bundle5.js:29:414126)

Import trace for requested module:
node:os
./node_modules/@prisma/client/runtime/library.mjs
./node_modules/@auth/prisma-adapter/index.js
./auth.ts


> Build failed because of webpack errors
```

### How to reproduce

1. Clone the project from the reproduction URL & npm install.
2. Run npm run dev, the server will start and this error will be displayed:

![Image](https://github.com/user-attachments/assets/bc7bf83f-65fd-48ae-9e20-0baee3097ef9)

### Expected behavior

For proper operation need to downgrade 'prisma', '@prisma/client' to version 6.3.1 and '@auth/prisma-adapter' to version 2.7.4.

![Image](https://github.com/user-attachments/assets/bc6e07a0-125e-4d1a-af3e-ee40f4c4bfa3)

**Comment by CharlesABJ** [comment]
I had the same problem

The solution was to delete the file middleware.ts

**Comment by dragos-cojocaru** [comment]
@zntb Have you found a solution for this?

**Comment by zntb** [comment]
> [@zntb](https://github.com/zntb) Have you found a solution for this?

I use @auth/prisma-adapter v2.74 with  @prisma/client v6.3.1, this works. Unfortunately I have no other solution.

**Comment by dragos-cojocaru** [comment]
I tried these version, but it still doesn't work for me.

**Comment by dragos-cojocaru** [comment]
Solved this by using `import {getToken} from 'next-auth/jwt';` instead of `import {auth} from '@lib/auth';` in `middleware.ts` to get the user auth state. I wonder why upgrade Guide (NextAuth.js v5) says to use `import {auth} from '@lib/auth';` which doesn't work in our case. @balazsorban44 @ThangHuuVu

**Comment by ThangHuuVu** [comment]
I think this is also fixed by https://github.com/nextauthjs/next-auth/pull/12755
will cut a release soon for you to retry.

**Comment by dragos-cojocaru** [comment]
@ThangHuuVu I tried the latest version. Unfortunately it didn't solve the problem for me.

**Comment by zntb** [comment]
**Prisma 6.7.0 solved the problem!**

Some modifications need to be made:
1. In schema.prisma:
```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../generated/prisma"  // Add this line
}
```
2. In prisma.ts:
```ts
import { PrismaClient } from '../generated/prisma';  // Change the path to this

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
```
Everywhere you import the `PrismaClient` change the path to  `'../generated/prisma'`

**I updated the repo with solution:** <https://github.com/zntb/authjs-prisma-bug>
