### ISSUE TITLE
TypeORM + Postgress: Unable to sign in The sign in link is no longer valid.

### ISSUE THREAD

**Issue by Santokua** [nextauthjs/next-auth#1968]
## Question 💬

Hey! I faced problem with Email provider. I cannot verify Email request, it says:

Unable to sign in The sign in link is no longer valid.
![image](https://user-images.githubusercontent.com/54191486/117751708-9a2bdf80-b226-11eb-8ee7-8a5c79d8d3e1.png)

## How to reproduce ☕️

- Use TypeORM + Postgres + FakeSMTP (http://nilhcem.com/FakeSMTP/)
- Copy link from FakeSMTP (mine: http://localhost:4600/api/auth/callback/email?=
email=3Dtest%40test.com&token=3Dec8263cb528ac8014436e09f19727e21131d8c0ced9=
9adc09abf010f5938a3b6)
- Try to validate

Video example: https://i.imgur.com/n7TWTSZ.gif

-------------------------------------

Sometimes it's throwing (even on Email sending request)
(node:24911) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isConnected' of null

![image](https://user-images.githubusercontent.com/54191486/117752980-c7798d00-b228-11eb-9c68-68112ab7bd4b.png)

**Comment by balazsorban44** [comment]
I think I found the problem. I'll try to fix it in the following days and let you know here.

**Comment by Santokua** [comment]
> I think I found the problem. I'll try to fix it in the following days and let you know here.

Thank you!

**Comment by balazsorban44** [comment]
I pushed a fix here: https://github.com/nextauthjs/adapters/commit/ff3f3e0f402f769677fcca831473c2a9c24ad646

If you re-run `npm install`, it should update the `@next-auth/typeorm-legacy-adapter` version in your `package-lock.json` or `yarn.lock`, and hopefully, the problem will be resolved. Could you please verify?

**Comment by investorhubcom** [comment]
Hi, I updated to 0.0.2-canary.128 but I am still getting an error
![image](https://user-images.githubusercontent.com/83321653/117817764-edf1f500-b235-11eb-8e48-81657b846513.png)

**Comment by balazsorban44** [comment]
Update: I reverted my attempts of a better connection handling in https://github.com/nextauthjs/adapters/commit/0b5d8adb191e0929f9322a084ba74badd1643d43

This means that the code should be back to how it was pre-moving the adapters out of the core. If you still experience issues, it indicates that the original implementation had this kind of problem as well!

Could you please run the commands I suggested above and see if it helps this time? (The adapter version this time is`0.0.2-canary.129`) If not, we will have to take a closer look at the adapter implementation.

**Comment by lcdproductions** [comment]
sorry if this comes off the wrong way - but is there not test coverage covering this adapter?

Magic sign-in is one of the core reasons we went with next-auth and magic sign-in broke as soon as I fired up the app with the update.

**Comment by balazsorban44** [comment]
And I'll be straight about it. Unfortunately, no the adapter is not tested at the moment, which is terrible, and we are aware of it. The previous main maintainer had plans adding good tests, but unfortunately being busy with work has never come to it. It is absolutely on our radar to test the adapters, and generally the source code of `next-auth`. Sine parts would be more straightforward, than others, but we are starting with the client side code testing. See #1937.

**Comment by followbl** [comment]
@balazsorban44 if you or powers to be broke down https://github.com/nextauthjs/next-auth/issues/1937 it to some bite sized tasks - I would be more than willing to help. This library is awesome and would love to help y'all ship with more confidence with some great tests.

**Comment by balazsorban44** [comment]
@investorhubcom It seems unrelated, as it uses JWT (judging from `getToken`), which does not touch on the adapters code. You seem to have a custom API handler at `/api/account/getAccount`, so adding it to your reproduction of the new issue would be great. It seems like something is not set correctly. If I had to guess, you either set https://next-auth.js.org/configuration/options#secret or https://next-auth.js.org/configuration/options#jwt > secret wrong. But please open a separate issue with a reproduction, thanks!


@followbl that is nice to hear! Do comment on that issue, and we will get back when we have a rough plan of what and how we want to test, or give your suggestion there!

**Comment by Santokua** [comment]
@balazsorban44 it's quite hard to make it work on sandbox. SMTP doesn't work there at all, no idea why. I can provide access to my repository for you, so you only will need to specify your database name and SMTP.

**Comment by Santokua** [comment]
@balazsorban44 I sent invite to you

**Comment by balazsorban44** [comment]
I'll have a look, thanks for the invite

**Comment by Santokua** [comment]
@balazsorban44 I found out the problem. Problem is SMTP client or something like this. 

This line 
`http://localhost:4600/api/auth/callback/email?=
email=3Dtest@test.com&token=3D43efc1e2ceddf0601ef6325276d1552=
a028be8a460a4df3ee149edbef980a70d`

Should be like:
`http://localhost:4600/api/auth/callback/email?email=test@test.com&token=43efc1e2ceddf0601ef6325276d1552a028be8a460a4df3ee149edbef980a70d`

So:
Every **3D** and **=** symbols should be removed.

**Comment by balazsorban44** [comment]
I seemed to have lost access to your repository, so I cannot see your code anymore. Also, I am not really sure what is happening with the encoding, but here is the relevant source code: https://github.com/nextauthjs/next-auth/blob/0fae0c7a8eb224964e38da409ecb9ba0497e8c50/src/server/lib/signin/email.js#L31

**Comment by Santokua** [comment]
@balazsorban44 That's not my code problem but SMTP fake clients. This can issue is completed and if i will face something similar in production i will re-open and inform you! Thanks!

**Comment by Asywalkers** [comment]
Hi guys I have the same problem? Have you any idea?
