### ISSUE TITLE
Live demo broken

### ISSUE THREAD

**Issue by UnsolvedCypher** [nextauthjs/next-auth#2039]
## Description 🐜

The [live demo](https://next-auth-example.vercel.app/) of NextAuth.js is broken for me in Firefox. On the "sign in" page, clicking any of the sign-in options doesn't do anything or provide any useful logs.

## How to reproduce ☕️

1. Open Firefox
2. Navigate to https://next-auth-example.vercel.app/ and click "Sign in" at the top
3. Attempt to sign in

## Screenshots / Logs 📽

![nextauthjs](https://user-images.githubusercontent.com/3170853/119075654-1b216e80-b9bf-11eb-8a89-6e0dd983ff20.gif)

**Comment by balazsorban44** [comment]
Just checked in Chrome, and the issue is happening there as well! This will need more investigation!

**Comment by balazsorban44** [comment]
UPDATE:

@UnsolvedCypher This was luckily a small fix!

A while ago, Vercel changed their URLs, so we just need to adapt:
Every reference to .now.sh has to change accordingly:
`https://next-auth-example.now.sh` -> `https://next-auth-example.vercel.app`



Ref: https://vercel.com/changelog/urls-are-becoming-consistent

I did change the `NEXTAUTH_URL` env variable in our Vercel dashboard, but our connected providers must be updated as well (change their allowed callback URLs accordingly.) Unfortunately, most of these provider apps were set up by @iaincollins, and only he has access to them, so I'll try to contact him.

**Comment by balazsorban44** [comment]
I pushed a commit that updated our references in the docs to `.vercel.app` as well.

Still waiting for @iaincollins to change the callback URLs. If I don't get an answer in a reasonable amount of time, I might just set up some new OAuth clients for our test site. I assume it is a fairly bad advertisement for us that our own example/demo project does not work... :grimacing:

Thinking of maybe waiting a week. If you don't hear back from me until then, just mention me in this issue, and I'll do the necessary changes!

**Comment by iaincollins** [comment]
Oh no, I didn't realise they had 2FA tied to my phone number for a bunch of these accounts.

Will get on that today and update with what I have fixed/what's outstanding.

**Comment by balazsorban44** [comment]
@iaincollins have you had a chance yet? I just tried the github sign-in and still getting an error. I'm thinking to just set up some new clients soon, if nothing happens. It is a relatively easy task to update some URLs, and I think we should highly prioritize our own example to work.

**Comment by iaincollins** [comment]
I have updated the configuration and resolved the issue for the following providers:

* Google
* Facebook
* Twitter
* GitHub
* Auth0

I have tested these and confirmed they are working.

Note: As it uses a temporary in-memory database, if you sign out with one account and immediately sign in with another account and they share the same email address, it will prompt you to sign in with the original account you used. This is intentional, although the flow is currently sub-optimal.

Not resolved:

* Apple

This requires a paid developer account and is generously provided by @geraldnolan, who also wrote the Apple provider (which was particularly tricky as we didn't have any other form of OpenID support at the time). We should reach out to Gerald to see if he is able to update the callback URL to `https://next-auth-example.vercel.app/api/auth/callback/apple`.

May temporarily remove the Apple Sign In option until this is resolved.

**Comment by iaincollins** [comment]
@balazsorban44 Thanks for changing the URLs in the dashboard and for poking me about this issue!

**Comment by balazsorban44** [comment]
I propose that we remove the Apple provider for the time being, so we can close this issue. I think our hosted example can be very simple, and its only purpose is to showcase our versatility. You listed a number of other providers that already work, it would be more than enough for evaluating `next-auth`. If not, we could rather link to the documentation: https://next-auth.js.org/configuration/providers#available-providers

**Comment by iaincollins** [comment]
Done! Have commented it out for now, with an explanation.

I might reach out and see if we can get a free Apple developer account.

**Comment by geraldnolan** [comment]
@iaincollins sorry missed this. I can update it later tonight.
