### ISSUE TITLE
Disable broadcasting as it creates issues with refresh token rotation

### ISSUE THREAD

**Issue by mtt87** [nextauthjs/next-auth#2071]
## Description 🐜

Took me a bit of time but I think I finally understood why we were seeing so many errors related to refreshing the token in our app.

I'm following the suggested setup to refresh tokens https://next-auth.js.org/tutorials/refresh-token-rotation which works fine.

The issue is the broadcasting that if you have more than 1 tab open with your web app, it will trigger a session check for EVERY tab and then you end up triggering the `refreshAccessToken()` function multiple times simultaneously with the same set of parameters (same `refresh_token`)

This creates an issue because the first request will be successful and obtain a new `access_token` paired with a `refresh_token` while all the other calls that were made will get a 400 since the old `refresh_token` has just been invalidated by the first successful call.

Simplest way to fix this would be to have the option to disable broadcasting and let each tab try to refresh the session only when focused.

## How to reproduce ☕️

In the app try to set a `clientMaxAge` of 10 seconds
```js
      <AuthProvider
        session={pageProps.session}
        options={{
          clientMaxAge: 10,
        }}
      >
```
Then add a log in `[...nextauth].js` `jwt` callback
```js
    async jwt(token, user, account, profile) {
      console.log('JWT')
```

Open 2 tabs and move between them, you will notice that every 10 seconds there are 2 calls being made to refresh the session and 2 console logs
```
JWT
JWT
```

I can create a codesandbox later after I finish work if needed but it's pretty simple to verify I believe 😄 

I'm using `"next-auth": "3.23.3"`

**Comment by balazsorban44** [comment]
If true, that would be a very nice fix! So basically there is a race condition here, where two calls made to the /ap/auth/session endpoint will both try to refresh the token, and the second one finishing fails. Right?

**Comment by mtt87** [comment]
Yes correct, let me explain it better with a practical example.

Imagine you issue `access_token` that expire after 10 minute and a `refresh_token` that lasts for 1 month that you can use to refresh your `access_token`.

The way it works is that when you exchange the `refresh_token` you obtain a new `access_token` but also a new `refresh_token`, which means that the previous `refresh_token` is now invalid.

 Now imagine a timeline where you have 3 tabs open with the same app `my-app.com`

00:00 the user opens `my-app.com` on a tab and login into the app, the user now has a session that contains
```js
{ access_token: "at1", refresh_token: "rt1", expire_in: "15min" }
```
00:01 the user opens another tab with `my-app.com` and after a brief check, the user is already logged in because there is a valid session
00:02 the user opens another tab with `my-app.com` and after a brief check, the user is already logged in because there is a valid session
00:03 the user open another tab with a different website and starts reading an article for 5 minutes
-- 5 min later --
05:00 the user decides to go back to `tabA` where your app `my-app.com` is open, this triggers a broadcast of the `session` event to tell all the other tabs where your app is open to check the session
05:01 all the 3 tabs have made a call and the token is still valid so nothing happens, just to confirm we still have the originally exchanged `access_token` and `refresh_token`
```js
{ access_token: "at1", refresh_token: "rt1", expire_in: "15min" }
```
05:02 the user opens another tab and keeps browsing
-- the user goes out for lunch, 30 min later --
35:00 the user is back from lunch and selects one of the `my-app.com` open tabs
35:01 the tab broadcasts the `session` event and all 3 tabs are checking at the same time if the session is valid
35:02 the `access_token` is now expired so all the 3 check session calls have triggered `refreshAccessToken()`

1st request is successful: exchange the `refresh_token` `rt1` with a new `access_token` and `refresh_token` so the `jwt` callback is returning the updated token as following
```js
{ access_token: "at2", refresh_token: "rt2", expire_in: "15min" }
```
2nd and 3rd request fail with 400 because they are trying to use the `refresh_token` `rt1` that has just been invalidated so the `jwt` callback is returning the updated token as following
```js
{ access_token: "at1", refresh_token: "rt1", expire_in: "15min", error: "RefreshAccessTokenError" }
```

Now we have 3 big problems:
1) This happens in a window of milliseconds and it can trigger a rate limit, imagine you have 5 tabs open it's 5req/s, generally these auth endpoint have a rate limit to avoid bruteforcing etc
1) We added `error` to the token and the client now believes that the the refresh token exchange was unsuccessful (we send the user to the login again)
1) We have lost forever the latest correct `access_token` and `refresh_token` because the last call that was made returned the previous token with the error
```
// The function was called with the old token containing "at1" and "rt1"
{ ...token, error: "RefreshAccessTokenError" }
```

**Comment by balazsorban44** [comment]
Love the details, make sense! I'll come back to this, thank you!

**Comment by mtt87** [comment]
Yes but unfortunately the race condition is not solvable in a stateless serverless environment that’s why I think the only way to solve it is to prevent this from happening due to the broadcasting.

To solve this at the server level we would need a persisted state of the refresh token requests that are in flight in order to stop the subsequent request and instead wait but it starts to become very complex :)

**Comment by balazsorban44** [comment]
I see, and I was thinking the same. fixing it by make it possible to disable broadcasting is one way, but what about clientside code where after some stale time, let's say two requests are going to a external api and they retrieve the access token from session?

I know react-query does fetch deduplication, so maybe we need to do something similar in our client code?

**Comment by mtt87** [comment]
I’m using SWR for the requests which works similarly to react-query for the deduplication and that’s fine. The problem imho is not deduplicating on the client side for a single page but trying to deduplicate for all the pages.

I’m trying to think at the problem from a different perspective: how about the broadcast is not saying “hey all tabs please refresh the session” but rather “hey I’m
TabA and I’m going to refresh the session”.
Then all the other tabs can wait for either a success event, and after that they can refresh their session or a fail event which means they should logout.

**Comment by balazsorban44** [comment]
Don't know if SWR does that, but react-query deduplicates site-wise, using a React Context.

What you are saying how to go about broadcasting does sound interesting, and I would rather not introduce new options, if we can work something out transparently for this.

**Comment by mtt87** [comment]
> What you are saying how to go about broadcasting does sound interesting, and I would rather not introduce new options, if we can work something out transparently for this.

Going to bed now, I’ll write down a proposal tomorrow with some scenario

**Comment by mtt87** [comment]
On my side the main question for you @balazsorban44 is:

### **What problems are we trying to solve broadcasting the `getSession` event?**

> I see, and I was thinking the same. fixing it by making it possible to disable broadcasting is half way, but what about clientside code where after some stale time, let's say two requests are going to an external api and they use the access token from session?

This problem has nothing to do with next-auth because you can have 100 requests to external API at the same time and they will not trigger the `jwt()` callback even if you are using a lambda to proxy the requests, I just tested the scenario where I have a serverless API that's using `getToken()` and **it doesn't trigger `jwt()`**
```js
async function handler(req: NextApiRequest, res: NextApiResponse) {
  const token = await getToken({
    req,
    secret: process.env.NEXTAUTH_SECRET,
    encryption: true,
    signingKey: process.env.NEXTAUTH_SIGNIN_KEY,
    encryptionKey: process.env.NEXTAUTH_ENCRYPTION_KEY,
  })
  // call the API with the access_token contained in the encrypted token object
  ...
}
```

----

Writing down the full picture so if someone wants to read they have more context.

## Refresh token rotation scenario

A session is based on session cookies that are set on successful login by the server lambda.
```
__Secure-next-auth.session-token
__Host-next-auth.csrf-token
__Secure-next-auth.callback-url
```

The most common scenario is  the oAuth based authentication where an oAuth provider on successful login will issue an `access_token` and a `refresh_token`.

If you want to have a completely stateless authentication (no databases needed) then you will add these tokens to the JWT.
Due to the nature of these artifacts, it's not a good idea to put them plain unencrypted in a JWT but rather **use an encrypted** JWT **(JWE)**.

Next-auth supports this by adding
```js
jwt: {
  encryption: true,
  secret: process.env.NEXTAUTH_SECRET,
  signingKey: process.env.NEXTAUTH_SIGNIN_KEY,
  encryptionKey: process.env.NEXTAUTH_ENCRYPTION_KEY,
},
```

Next-auth uses the `jwt()` callback to control this, so in the case of a scenario where you have a refresh token you want to add a check to make sure if the `access_token` is expired, try to refresh it and return the new `access_token` and `refresh_token`.

Note: the `jwt()` callback is triggered every time the user is checking the session, either by calling `getSession()` or with the `useSession()` hook.
What they do is calling `GET /api/auth/session` behind the scenes.

```ts
async jwt(token, user, account, profile) {
  // Return previous token if the access token has not expired yet
  if (Date.now() < token.expiresAt) {
    return token
  }
  // Access token has expired, try to update it
  return refreshAccessToken(token)
},
```

`refreshAccessToken()` is a function to exchange the `refresh_token` for a new pair of `access_token` and `refresh_token` that are returned and included in the updated encrypted JWT (JWE).
**Important:** the previous `refresh_token` is instantly invalidated.

```ts
async function refreshAccessToken(token: JWT) {
  try {
    const refreshedTokens = await request(...)
    return {
      ...token,
      accessToken: refreshedTokens.access_token,
      expiresAt: Date.now() + refreshedTokens.expires_in * 1000,
      refreshToken: refreshedTokens.refresh_token ?? token.refreshToken, // Fall back to old refresh token
    }
  } catch (err) {
    return {
      ...token,
      error: 'RefreshAccessTokenError',
    }
  }
}
```

## Next-auth broadcasting

Next-auth creates automatically a broadcast channel on every tab you open with the same web app.
https://github.com/nextauthjs/next-auth/blob/main/src/client/index.js#L39
Every tab is listening for 2 `session` events:
- `getSession`: this is broadcasted whenever you unfocus and focus back one of the tabs where your web app is running, telling the other tabs that they should check their session and in the scenario where you have 3 tabs open it will trigger simultaneously 3 API calls to check the session
- `signout`: this is telling the other tabs that the user is not longer logged in so they should sync and logout the user as well

## Broadcasting issue with refresh tokens

If you have 3 tabs checking the session and triggering the `jwt()` callback 3 times in the same moment, it means that there are 3 `refreshAccesstoken()` being called, which means that there are 3 API calls to exchange the token, all of them with the same `refresh_token` currently available.

1st call: `200` successful, receives the new `access_token` and `refresh_token` that are returned and added to the encrypted JWT to substitute the existing `access_token` and `refresh_token`.
2nd call: `400` error, the `refresh_token` used to call the function is now invalid as it's just been used. We add the key `error: "RefreshAccessTokenError"` that's added to the session so the frontend now believes that the user needs to signin from scratch.
3rd call: `400` error, same as above

The problem is that the 2nd and 3rd call are basically "overwriting" the 1st call and now the latest JWT contains the error and the wrong tokens. The refreshed tokens are now lost and unrecoverable.

### Serverless stateless environment

It's important to understand that we are in a stateless serverless environment.
We cannot assume that the 3 check session calls mentioned above are going to the same lambda function, they could be different lambda function and all of them are isolated.
We want to keep a stateless auth so there are no databases involved and nothing can be persisted due to the ephemeral nature of a lambda function.

# Proposed  solution: option to disable broadcasting some events

If we add an option to disable the broadcasting of the `getSession` event, we can prevent this from happening at the root.
What does it mean in a scenario where we have 3 tabs?
1st tab that gets focus will check the session and trigger a refresh token and update the session accordingly.
2nd tab and 3rd tab are not aware this happened BUT because updating the session with the new tokens basically means to update the cookies, the 2nd and 3rd tab got the session updated automatically in case they have some background stuff (for example they are polling an API from time to time)
When the user opens the 2nd tab it will check its session and nothing happens as the cookie has already been updated with the new tokens not yet expired, same would happen to the 3rd tab.
Since we are still broadcasting the `signout` event, in case the user decides to logout or their tokens are expired and can't be refreshed, all the other tabs will still be notified.

**Comment by mtt87** [comment]
@balazsorban44 sorry to bother you, did you have a chance to read my last comment?
My question for you: what problems are we trying to solve broadcasting the getSession event?

**Comment by balazsorban44** [comment]
Will have a proper read of this in the next few days, I hope. I actually just had to deal with this problem at work, came to a conclusion and used some different approaches, but ultimately I think supporting token rotation will be something that will need some more thinking. This has certainly become rather a feature request than a bug.

**Comment by mtt87** [comment]
Thanks for the update, I see your point, on my side I was more inclined to define this a bug since refreshing a token feels to me like a basic necessity rather than an "additional feature" for modern web apps 😄 
Anyway I'll wait for your next reply and once agreed on the approach I'm happy to contribute if need my help.

**Comment by balazsorban44** [comment]
I would only call it a bug, if the functionality is already built-in, but do not deliver what it is meant to. A feature request is when we want to introduce a functionality that hasn't existed yet in the library. We still do not have built-in token rotation, and partially from the above mentioned issues, it is not trivial at the moment.

I have looked around the web to see how others are doing it, and honestly, I haven't found a go-to solution. The main problem here be it tab sync or other reasons of race conditions, when a token refresh is in flight and a new request wants an updated token, the old refresh token will be used again, which will lead to a problem.

According to my findings, the only way to avoid this is orchestrating (read deduplication) the client-side requests to `/api/auth/session`. In our case at work, we are using https://github.com/nextauthjs/react-query which does deduplication automatically. Basically you want to make sure that whenever a request goes to `/api/auth/session`, other calls rather "subscribe" to that response, than start a new request. When using https://github.com/nextauthjs/react-query broadcasting is not an issue, as we don't need the `useSession` hook from `next-auth/client`.

I think if we want to move forward with built-in token rotation, we will need to complicate our clilent-side code slightly, so it handles deduplicated requests to `/api/auth/session` correctly. I don't think it would be as easy as it sounds, but I might be wrong. In any case, I would like to hold this off until we have a better client implementation #1473

**Comment by mtt87** [comment]
Sorry but unless there is something that I didn’t understand, I don’t think what you are saying is correct and you might not be looking at the problem from the correct angle.
The problem doesn’t exist when you have a single tab open but only when you have multiple tabs.
When you have a single tab open, since you are wrapping the entire application in the session provider, it looks like even with multiple components depending on useSession you only get 1 api call.
As mentioned before even when calling a lambda API and using getToken utility, that doesn’t trigger a session update as it doesn’t trigger the JWT callback.
Deduplicating requests on a single tab is definitely possible as you said with stuff like react-query or useSWR, but it seems completely irrelevant to the problem.
The problem will still be there unless you deduplicate across all the open tabs.

Sorry if I ask again but I don’t think you ever replied to my question: what problem is next-auth trying to solve with the tab sync via broadcasting? 

Thanks for your time and patience

**Comment by balazsorban44** [comment]
OK, so we might have diverged at to `react-query` before I managed to check that the built-in `Provider` actually de-duplicates in a single tab scenario, but after some thinking, yes, it's probably true (https://next-auth.js.org/getting-started/client#options).

So in theory, a single boolean flag to disable broadcasting would do it then? Unless there is a more complicated way that would make it possible to de-duplicate even across open tabs? :smile:

**Comment by mtt87** [comment]
I think the only problematic broadcast event (in this scenario) is the `getSession` event.
The `signout` event is actually useful so I would leave the option to disable only a single event rather than disabling every broadcast.

Without broadcasting `getSession`, this is what should happen in a multi tab scenario, you focus the first tab
- request to update the session -> token expired -> request to refresh the token -> if successful `set-cookie` header will update the session with the new JWT containing the new `access_token` and `refresh_token`, this being a cookie is immediately reflected in every tab by the browser automatically as it's a domain cookie so if there are any background polling API calls in the other tabs, they will use the updated cookie with the new tokens

...after a minute you focus the 2nd tab

- it will request to update the session -> `access_token` still valid -> return exsiting tokens in the session cookie, all good

**Comment by HarunKilic** [comment]
I have almost the same issue. The problem is not the broadcasting tho, but regarding to refresh token rotation. 

I am using next-auth along with apollo (graphql), so whenever there is request to the API, it will go trough amount of queries to check if the access_token is alive.  

The problem im having is like: 

In this scenario i have 3 request. 
1. sending request with valid access_token, no need to update anything. -> Success response
2. sending request with expired access_token, need to update access and refresh token -> gets new tokens then success response
3. sends the request before 2. can insert the new tokens, tries to send old refresh_token -> gets Error, due to invalid refresh token. 

Haven't actually tried how it reacts with multiple tabs, but will try it tomorrow.

**Comment by mtt87** [comment]
@HarunKilic 

If I understand correctly your problem is related to the fact that you are using `getSession()` on the server when receiving the request so you are triggering the refresh token if the current `access_token` is expired.

Interesting, this means that you are saving the `access_token` in the session which means that it becomes visible to the client as well, I'm not sure if there are any security implications. I'm instead saving it in the JWT token (encrypted) so only the server side has access to `access_token` and `refresh_token` with the `getToken()` method called on a server side lambda function.

I think in your scenario the broadcasting will also show the same problem but for you the problem exist also on a single tab open. A possible workaround could be if apollo client can batch requests but still, it's not a perfect solution as there is always going to be a range of time when the token is being refreshed and a request maybe triggered by a user action will still end up in the same problematic situation.

🤔  A possible solution but more complicated would be to use a database like Redis where you can store what token refresh are in flight and pause all the others but sounds a bit more complicated.

**Comment by HarunKilic** [comment]
> @HarunKilic
> 
> If I understand correctly your problem is related to the fact that you are using `getSession()` on the server when receiving the request so you are triggering the refresh token if the current `access_token` is expired.
> 
> Interesting, this means that you are saving the `access_token` in the session which means that it becomes visible to the client as well, I'm not sure if there are any security implications. I'm instead saving it in the JWT token (encrypted) so only the server side has access to `access_token` and `refresh_token` with the `getToken()` method called on a server side lambda function which does NOT trigger a session check.
> 
> I think in your scenario the broadcasting will also show the same problem but for you the problem exist also on a single tab open. A possible workaround could be if apollo client can batch requests but still, it's not a perfect solution as there is always going to be a range of time when the token is being refreshed and a request maybe triggered by a user action will still end up in the same problematic situation.
> 
> Or you can follow the way we are doing it by proxying all the calls through the server lambda that can obtain the `access_token` with `getToken()` without triggering a session check/token refresh.
> It means that it can throw 401 and you can handle the error on the frontend perhaps trying to signin the user or retry after a few seconds...
> 
> 🤔 A possible solution but more complicated would be to use a database like Redis where you can store what token refresh are in flight and pause all the others but sounds a bit more complicated.

The reason I use `getSession()` is to trigger the `JWT callback`. As it checks if the `access_token` is still alive. 
I have to check it everytime, as some requests can have extra information if the user is logged in. 

Bulk solution will not really solve the problem, as it will occur on the frontend too. 

The Redis solution would solve it, but it becomes much more complicated than what it actually should be.

**Comment by mtt87** [comment]
> The reason I use `getSession()` is to trigger the `JWT callback`. As it checks if the `access_token` is still alive.
> I have to check it everytime, as some requests can have extra information if the user is logged in.

I understand because most likely you want to use the `access_token` as `Authorization: Bearer ${access_token}` when making some authenticated requests for the logged in user.
What I'm saying is that if you use an encrypted JWT where you store the `access_token` and `refresh_token` rather than using the session, then you can call `getToken()` which does not trigger a check of the session (and therefor not a refresh of the token if necessary)

In that case the session is only checked if you set `clientMaxAge` lower than your `access_token` expiry so after that time, the session will not be fetched from the client cache but it will call the server same as using `getSession()` and it will trigger an update of the refresh token, that's stored in the JWT so the session cookie gets updated.

This way you will not have any issue with a single tab open but only the issue with multiple tabs open due to the broadcast 😄

**Comment by HarunKilic** [comment]
> > The reason I use `getSession()` is to trigger the `JWT callback`. As it checks if the `access_token` is still alive.
> > I have to check it everytime, as some requests can have extra information if the user is logged in.
> 
> I understand because most likely you want to use the `access_token` as `Authorization: Bearer ${access_token}` when making some authenticated requests for the logged in user.
> What I'm saying is that if you use an encrypted JWT where you store the `access_token` and `refresh_token` rather than using the session, then you can call your authenticated APIs from a server lambda `/api/something` using `getToken()` which does not trigger a check of the session (and therefor not a refresh of the token if necessary)
> 
> In that case the session is only checked if you set `clientMaxAge` lower than your `access_token` expiry so after that time, the session will not be fetched from the client cache but it will call the server same as using `getSession()` and it will trigger an update of the refresh token, that's stored in the JWT so the session cookie gets updated.
> 
> This way you will not have any issue with a single tab open but only the issue with multiple tabs open due to the broadcast 😄

Thanks. I'll try it out tomorrow. But I think it's bad practice to know when the JWT token expiry length will be. Small problem compared to the other tho :D

**Comment by balazsorban44** [comment]
What we do is that we send the `access_token` to the frontend, using `react-query`, we read the session on each API request. If the token is not expired yet, it just returns it from the cache, but if it needs refreshing, `react-query batches/dedupes the session calls, even if multiple parts of your app made an API call at the same time. There will be one request and multiple subscriptions to that result.

**Comment by mtt87** [comment]
> @mtt87 with your solution, wouldn't you have to make sure that there is always only a single request to your API at one point in time?

Not really because if 1 or more requests are failing because the `access_token` is expired, then the API is returning `401` and in the app I trigger a signin for the user again from scratch, which means that a new session cookie with the new `access_token` and `refresh_token` is obtained.

Imagine you have 1 tab open and 3 requests are triggered at the same time
1st response will be `401` and will trigger a new signin
2nd response will be `401` but it won't have any effect as the page has been "closed" and the user is signin in from scratch
3rd response, same as above

That said I'm using `swr` which has deduplication built-in yes https://swr.vercel.app/advanced/performance#deduplication
If they are using apollo for the GraphQL I believe it has also deduplication enabled by default https://www.apollographql.com/docs/react/api/core/ApolloClient/#querydeduplication

OT: is it safe to store the `access_token` in the session? Feels more safe to never expose it to the client imho as that means it will be readable by the entire app vs proxying the call with the server lambda where the token is retrieved with `getToken()` from the encrypted JWT

**Comment by balazsorban44** [comment]
Exposing `access_token` to the front end is certainly a trade-off, but I believe with a short lifetime, it is OK. Also depends on what the `access_token` actually gives access to. In our case it is mostly read operations, so no real damage can be done, even if it gets exposed somehow. It is certainly more secure the way you are doing it.

**Comment by mtt87** [comment]
If you wanna test my changes before merging or publishing a new package, I've managed to publish it on my scope temporarily https://www.npmjs.com/package/@mtt/next-auth and I'm using it in our app https://developer.tru.id/docs
I'm gonna keep an eye tomorrow to see if the refresh token errors are disappearing and there are no other new issues (we have Sentry + Kibana logs)

**Comment by HarunKilic** [comment]
> If you wanna test my changes before merging or publishing a new package, I've managed to publish it on my scope temporarily https://www.npmjs.com/package/@mtt/next-auth and I'm using it in our app https://developer.tru.id/docs
> I'm gonna keep an eye tomorrow to see if the refresh token errors are disappearing and there are no other new issues (we have Sentry + Kibana logs)

Anything new? I am considering to use only access_token, just because of this issue :/

**Comment by mtt87** [comment]
On my side with the `getSession` event broadcasting disabled, I've not seen any issue in the kibana+sentry logs 🤞

**Comment by HarunKilic** [comment]
> On my side with the `getSession` event broadcasting disabled, I've not seen any issue in the kibana+sentry logs 🤞

Sounds great! I think i know what my problem is. When running first refreshtoken, it goes smoothly, but when it runs second time, it still has the old states. So it will try to refresh the token with old token, and will obv get error due to old/invalid refreshtoken. 

I am not sure if it is because the client side and server side conflicts regarding to states. 

Tried to use getToken() but i get errors. 

I think it would fix the problem, if i could only refresh the token manually or with fixed time and disable it when using getSession/useSession. 

Not quite sure how it would look like.

**Comment by mtt87** [comment]
> Tried to use getToken() but i get errors.
Maybe post a gist  with the full setup you are using (the relevant parts at least) so I can check.

I don't have problems using `getToken()`, this is my setup (I removed some parts that are not relevant)
https://gist.github.com/mtt87/8fd4b92619ea2128eb027811c935ee68

**Comment by makezi** [comment]
@mtt87 I've refactored my `refreshAccessToken` function to match yours as well as used your `next-auth` package ([repo here](https://github.com/makezi/next-auth-refresh-token/tree/test-fix)) and still facing the same error on a single tab. 

I think @HarunKilic's situation is different as he mentioned in #2123 (also mentioned by me in #1455) in that server session doesn't save the updated refresh token - it's just uses the initial old access token/refresh token. 

You can test this in the repo I linked where the access token expires after a minute. If you were to click the "server" route after a minute you'll see logs that it will had successfully retrieved and updated the token values (access_token, refresh_token, expires_in, etc.). However, clicking "server" again will trigger only a **single** fetch from the session endpoint with still the old token values.

Unsure if disabling session broadcasting will solve this particular use case unfortunately unless something was missed?

**Comment by mtt87** [comment]
@makezi thanks for the repo to reproduce. I think you just discovered another bug 😄 

In your case the problem is that you've set `clientMaxAge` which according to the documentation should
```
        // Client Max Age controls how often the useSession in the client should
        // contact the server to sync the session state. Value in seconds.
        // e.g.
        // * 0  - Disabled (always use cache value)
        // * 60 - Sync session state with server if it's older than 60 seconds
```

But try to go to another tab, then wait a minute, then comeback to that tab and you will notice in the network inspector that a `session` API call has been made.

This seems to be a bug as with a `clientMaxAge = 0` it should NEVER contact the server but always use the cached value.

Your refresh token issue is due to the fact that when you focus the tab and hit refresh the page, you are triggering 2 refresh token requests
1) the one automatically triggered when you focused the tab
2) the one you manually triggered by refreshing the page

If `clientMaxAge` would work correctly, you would not see this issue because only 1 refresh token request would be triggered

cc @balazsorban44

**Comment by mtt87** [comment]
Actually that code comment is not accurate as the documentation says that it is the intended behaviour 
https://next-auth.js.org/getting-started/client#client-max-age
> When clientMaxAge is set to 0 (the default) the cache will always be used when useSession is called and only explicit calls made to get the session status (i.e. getSession()) or event triggers, such as signing in or out in another tab/window, or **a tab/window gaining or losing focus**, will trigger an update of the session state.

So this is another thing that in case you are using server side rendered pages you would need to have the option to disable.

**Comment by makezi** [comment]
Sorry, I'm not sure I'm understanding. That repo does contain your changes (`test-fix` branch) to disable broadcasting yet the problem still persists. As mentioned, the issue here is still happening on the single tab - there is no switching/focusing of tabs.

**Comment by hboylan** [comment]
> When a server side page loads and it's passing the `session={pageProps.session}` from what I understand the Provider should use that session instead of triggering a new session check on load

I encountered this issue as well. Passing a new session to `<Provider session={pageProps.session}>` on the client still causes it to make a call to `/session`.

**Comment by balazsorban44** [comment]
> > When a server side page loads and it's passing the `session={pageProps.session}` from what I understand the Provider should use that session instead of triggering a new session check on load
> 
> I encountered this issue as well. Passing a new session to `<Provider session={pageProps.session}>` on the client still causes it to make a call to `/session`.

#1473 is going to address this hopefully.

**Comment by hboylan** [comment]
@balazsorban44 Are you aware of any workaround in the meantime to prevent a client-side call when a valid session is passed to `Provider`?

**Comment by hboylan** [comment]
Ah, darn. Looking forward to #1473 then.

Looks like `react-query` also doesn't handle the session coming from `getServerSideProps`. 😭

**Comment by balazsorban44** [comment]
It does, but naturally, you have to pass it in a different way. See https://react-query.tanstack.com/guides/ssr#using-hydration

**Comment by HarunKilic** [comment]
> Unfortunately react-query doesn't match our use case. We need Apollo Client query our GraphQL service. Looks like I'll have find another way to "rehydrate" the session on the client without the extra `getSession` call.

Can u please come back if you find something?

**Comment by hboylan** [comment]
My workaround for now is to use a separate variable for the access token instead of relying on `useSession` as I would like.

1. Get session with `getServerSideProps`
2. Set session with `<Provider session={session}>`
3. Pass session to my Apollo Client `<GraphqlProvider session={session}>` instead of `useSession` internally
4. Set variable with access token to be used in request headers `let accessToken = session?.accessToken`
5. Call `getSession` to refresh tokens when necessary _and_ update the `accessToken` for continued use in Apollo Client

**Comment by makezi** [comment]
@balazsorban44 Since you're using https://github.com/nextauthjs/react-query at work, mind if I ask what properties/values are you passing to the `queryConfig` (i.e. `staleTime`, `refetchInterval`, anything else)? Might give it a go now to see if it works as a workaround/temporary solution.

**Comment by balazsorban44** [comment]
`staleTime` same as the `expires_in` of our OAuth provider's /token response, `refetchInterval` anything lower than that.

Then using https://react-query.tanstack.com/reference/QueryClient#queryclientfetchquery to get a session right before api calls adding an access_token.

that method dedupes session requests (where we refresh the token when soon expires) and uses cache if data is not stale.

**Comment by mtt87** [comment]
Just be careful that these solutions might fix issues on a single tab scenario but not work in a multi tab scenario.

**Comment by mtt87** [comment]
I think I've found the ultimate™ solution to our problem 😆  and it's actually pretty simple.
It's something that was invented 30+ years ago with databases to prevent this type of issues: 

**A lock mechanism.**

There is a draft proposal: https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API
And I found a polyfill to make this work with other browser by using `localStorage` as fallback.
https://github.com/aermin/web-locks

I built a simple prototype locally to see if it works but this can be easily added to `next-auth` I believe since it's just a couple of lines of code to wrap our get session call.
```js
locks.request("NEXT_AUTH:GET_SESSION", async () => {
  // this callback is executed only when the lock is released
  console.log("lock acquired at this point");
  // get the session
  await fetch session...
  // once done the lock is released
  console.log('lock released at this point')
});
```

With this solution we cover all the 3 scenarios:
- broadcasting `getSession` event while a session refresh is already in flight
- focusing a different tab while a session refresh is already in flight
- opening a new tab while a session refresh is already in flight

I recorded a quick video to show how it works
https://youtu.be/EH_LwRs17uo

I also checked the impact is minimal (less than 1kb gzipped)
```
# without the web locks polyfill
+ First Load JS shared by all     68 kB
# with the web locks polyfill
+ First Load JS shared by all     68.7 kB
```

What do you think @lluia @balazsorban44 ? 😄 

I will try to add it to next-auth and see if it's simple.
At the moment the only downside of the library is that it needs to be loaded on the client as it throws the classic error `window is not defined` but maybe a quick PR can fix this.
```tsx
const [locks, setLocks] = useState<LockManager>();
...
useEffect(() => {
  import("navigator.locks").then((m) => {
    setLocks(m.default);
  });
}, []);
```

**Comment by mtt87** [comment]
Okay I tested locally and it seems to be as easy as wrapping `getSession` around the lock request function
```js
import locks from "@mtt/navigator.locks"

export async function getSession(params) {
  return locks.request("NEXT_AUTH:GET_SESSION", async () => {
    const session = await _fetchData("session", params)
    if (params?.broadcast ?? true) {
      broadcast.post({ reason: "getSession" })
    }
    return session
  })
}
```

Just one thing to note: I forked the package to fix the `window is not defined` error and I asked the maintainer to fix it, in the meantime I published the fixed version with `@mtt/navigator.locks`

Btw the package is well tested according to the Web Locks API specification.

@balazsorban44 what's the best way to open a PR with this change? I fork `main` or `canary` or another branch?

**Comment by ndom91** [comment]
@mtt87 currently we are working against the `next` branch - your best bet is to fork that :+1:

**Comment by jacklimwenjie** [comment]
Just want to add have multiple tabs running the same app with `next-auth` isn't the only way to run into this race condition. 

Having a request that obtains the access token by `getSession()` that is parallel to `next-auth` token refreshing request will result in the parallel request access the old token and attempt to refresh the token again. 

This is a headache when there's a polling setup such as by using `useswr` hook.

**Comment by mtt87** [comment]
@jacklimwenjie my proposed change to use `navigator.locks` (check above) solves the issue you just mentioned (I'm using `useSWR` in my project)
There is only 1 caveat: you can't call `getSession()` on the server side.
To handle the server side unfortunately you would need a DB like Redis or something like Deno Broadcast Channels https://deno.com/deploy/docs/runtime-broadcast-channel
I've heard Vercel is working on something similar 😄

**Comment by jacklimwenjie** [comment]
> @jacklimwenjie my proposed change to use `navigator.locks` (check above) solves the issue you just mentioned (I'm using `useSWR` in my project)
> There is only 1 caveat: you can't call `getSession()` on the server side.
> To handle the server side unfortunately you would need a DB like Redis or something like Deno Broadcast Channels https://deno.com/deploy/docs/runtime-broadcast-channel
> I've heard Vercel is working on something similar 😄

That's cool! 
I was trying my own implementation of the "lock", where each time the jwt callback happens, I will push the refresh token request promise into an array and use `Promise.race()` or `Promise.any()` to resolve concurrent refresh token requests to just the first resolved refresh token request.

I am using `axios` as the fetcher for `useswr`. To ensure that the latest access token is set as Authorization header for each fetch request, I setup a request interceptor to query session by using `getSession()`.

Unfortunately, this approach causes memory issue and is not working very well, not sure what I missed. 

It's down to either investing more time in improvising refresh token rotation in `next-auth` or rework the authentication module with an alternative, but time is not in my favor so I have decided to just extend my refresh token TTL so that users don't have to re-login as often.

**Comment by mtt87** [comment]
@jacklimwenjie I would suggest you to not go down that DIY road 😄  and save a lot of headaches. It's a shame you had to compromise on security by increasing the refresh token TTL.

If you want I've implemented `navigator.locks` which is an experimental API (but there is a polyfill so it supports all the browsers) and I've published a forked version here https://www.npmjs.com/package/@mtt/next-auth (based on the lastest next-auth v3)
```
npm i @mtt/next-auth
```
It's just a few lines of code feel free to have a look https://github.com/mtt87/next-auth/commit/f0307db951d085420d0dc4b22ca824e6adac786c

This fixes all the issues with the client side calls as it creates a lock which a sync mechanism that works across different tabs.
The only caveat is that you cannot call `getSession()` on the server side but only use `getToken()`.

I opened a [PR](https://github.com/nextauthjs/next-auth/pull/2357) but the team decided to wait and release the v4 before considering this fix.

**Comment by mtt87** [comment]
Can you create a public repo to reproduce the issue? Hard to tell from your description, also I'm not sure it's related to this issue about refresh tokens 👁️

**Comment by DarthSomebody** [comment]
@mtt87 I'm using your Next-Auth fork, but the problem seems to still exist, although it might have at least gotten a bit better.
I observed 2 concurrent requests to session being made, coming from useSession on the client, both in different components on the same page. 
I set a breakpoint with my Node.js debugger. The jwt-function was called twice with the same session token, which had an expired access token, so both calls tried to refresh it, which led to one of them failing and logging the user out. Sounds like the same problem, still.

**Comment by mtt87** [comment]
@DarthSomebody interesting, could you provide more details? What browser / version? Even better if you have a repo to reproduce 😄  On my side with my fork I very very rarely see this happening but it's not 100% fixed I think there might be some race conditions not sure, I would love to know more about it.

**Comment by DarthSomebody** [comment]
I'm using Firefox Developer Edition 86.0b9. I have a small team using a CMS I developed with Next and Next-Auth, and they report being logged out once every 2-3 days (access token lifetime is 1h). They're using the latest versions of Chrome and Firefox.

I couldn't find a surefire way to reproduce it. I left my debugger on for more than a day, occasionally switching pages or closing/re-opening the tab, waiting until the access token is expired before I do something, and so on, until it finally hit the breakpoint I set where the refresh failed. Network Monitor in Firefox was showing 2 pending requests to session at that time. Unfortunately I don't know which action exactly caused this to happen.

I'll see if I can make a public repository with a shorter access token lifetime to reproduce it, but I don't have much time currently, so it might take a while until I can get to it.

**Comment by DarthSomebody** [comment]
bump.
(Still haven't had the time to look into it, unfortunately)

**Comment by mtt87** [comment]
Unfortunately without a repo to reproduce the issue, it's not easy to tell what's going wrong.
On my side it works using my fork 👁️

**Comment by KeyanNamaghi** [comment]
Does anyone know if Is there anything in Next Auth 4 that prevents this issue with multiple tabs causing this bug with refresh tokens? If I have multiple tabs open and leave the browser until the access token has expired both tabs are trying to refresh the token and it is resulting in the user being logged out

**Comment by mtt87** [comment]
Not at the moment unfortunately it doesn’t seem to be a very popular use case. 
I have a fork that prevent this under certain circumstances (only on client side calls) and I was working to update it to v4 but there are still a few bugs and typescript issues last time I checked around a month ago

**Comment by KeyanNamaghi** [comment]
That's annoying. I'm a bit confused why this isn't a more widespread issue, is there a different approach I could be taking that wouldn't result in this issue?

**Comment by DarthSomebody** [comment]
I solved it by using Redis, as @mtt87 suggested.

I'll provide a basic solution here, using [Redlock](https://github.com/mike-marcacci/node-redlock) and [ioredis](https://github.com/luin/ioredis). 
Redis needs to be installed on your server. For development on Windows I'm using [Memurai](https://www.memurai.com/get-memurai).

Place this at the top of the same file where your JWT-callback is in:
```js
import Client from "ioredis";
import Redlock from "redlock";

// See the ioredis and redlock docs for all the options
const redis = new Client();
const redlock = new Redlock([redis], {
    driftFactor: 0.01,
    retryCount: 10,
    retryDelay: 200, 
    retryJitter: 200, 
    automaticExtensionThreshold: 500
});
``` 

And here's the JWT-callback:
```js
const jwt = async (token, user) => {

    // This is only true on login
    if (user) {
        // Fill your token with the properties of your user object.
        return {
            expiresAt: /* the expire date of your access token*/,
            accessToken: /* your encrypted access token */,
            refreshToken: /* your encrypted refresh token */,
            user: /* user identifier */
        };
    }

    // Make sure the rest isn't executed twice for the same user at the same time.
    // You need some identifier for your user. Im my case it's token.user.
    return await redlock.using([token.user, "jwt-refresh"], 5000, async () => {

        // Get token either from redis cache or use the provided token.
        // This is crucial, because the provided token could be outdated due to a concurrent request.
        const redisToken = await redis.get(token.refreshToken);
        const oldToken = redisToken ? await JSON.parse(redisToken) : token;

        // Return old token if the access token has not expired yet.
        // My access token is alive for 1 hour, but I refresh it after 55 minutes, just in case.
        if (Date.now() < ((oldToken.expiresAt - 300) * 1000)) {
            return oldToken;
        }

        // Get your new token here, using oldToken.refreshToken as your refresh token
        ... 
        const newToken = {
            expiresAt: ...,
            accessToken: ...,
            refreshToken: ...,
            user: ...
        };
        
        // Save new token to redis, but use the provided refresh token as key.
        // This way, concurrent requests will get the new token when they check the redis cache.
        await redis.set(token.refreshToken, await JSON.stringify(newToken), 'ex', 300);

        // Return new token
        return newToken;
    });
};
```
Hope this helps someone.

Ideally, this mechanism should be part of NextAuth. This was quite a pain.

For testing, I reduced the expiry time for my access tokens down to 1 minute. To reproduce the issue, you can wait until the token is expired and then refresh multiple tabs at once. I just opened 3-4 tabs and quickly pressed F5 on each of them. They will call the session route with the same refresh token.

**Comment by balazsorban44** [comment]
I don't think we will introduce Redis as a dependency. This would make the entry to the library much harder, and isn't something to consider in many cases.

We have an Adapter interface though that can hopefully be a zero-config thing for most Providers.

**Comment by mtt87** [comment]
I think there are a few issues with your implementation @DarthSomebody , this is my suggestion with comments:

```js
const jwt = async (jwt, user, account, profile) => {
  // Initial sign in
  if (account && user && profile) {
    // Fill your token with the properties of your user object.
    const jwtToken = {
      expiresAt: "...",
      accessToken: "...",
      refreshToken: "...",
      userId: "...",
    };
    // Save the jwt token object in Redis the first time
    await redis.set(`token:${token.userId}`, JSON.stringify(jwtToken));
    return jwtToken;
  }

  // We can do this check also outside because if the access token is still valid
  // there should be no problem with concurrency and multiple requests
  if (Date.now() < (jwtToken.expiresAt - 300) * 1000) {
    return jwtToken;
  }

  // If we get here it means that the access_token is expired
  return await redlock.using([jwtToken.userId, "jwt-refresh"], 5000, async () => {
    // Always get the refresh_token from redis, that's the source of truth
    // NEVER get the refresh_token from the current jwt property
    const redisToken = await redis.get(`token:${jwt.userId}`);
    const currentToken = JSON.parse(redisToken);

    // This can happen when the there are multiple requests
    // and the first request already refreshed the tokens
    // so the consecutive requests already have access to the updated tokens
    if (Date.now() < (currentToken.expiresAt - 300) * 1000) {
      return currentToken;
    }

    // If it's the first request to refresh the tokens then
    // get your new tokens here, something like this:
    const newTokens = await getNewTokens(redisRefreshToken);

    const updatedJwtToken = {
      ...jwt,
      expiresAt: newTokens.expiresAt,
      accessToken: newTokens.accessToken,
      refreshToken: newTokens.refreshToken,
    };

    // Save new jwt token object to redis for the next requests
    await redis.set(`token:${jwt.userId}`, JSON.stringify(updatedJwtToken));

    // Return new jwt token
    return updatedJwtToken;
  });
};
```

- Bear in mind `JSON.parse()` and `JSON.stringify()` don't return a Promise so no need to use `await` in front 😄  (they are synchronous operations)
- I don't think it's a good practice to use as redis key the value (in your case you are using `redis.set(token.refreshToken`

**Comment by orangecoloured** [comment]
@mtt87 If we store tokens using user IDs as keys then there's a possibility to hijack the token mimicking the cookie with a known user id. I think the flow can be improved if the backend generates a device id that we later use as key. User IDs can be obtained easily looking at different request payloads, but the device ID is always stored privately in the cookie.

**Comment by mtt87** [comment]
> @mtt87 If we store tokens using `userId` as key, there's a possibility to hijack the token mimicking the cookie with a known `userId`. I think the flow can be improved if the backend generates a `deviceId` that we use as the key. `userId` can be obtained easily by looking at API requests payloads, but the `deviceId` is always stored privately in the cookie.

👋  I'm not sure about what you say, basically to "mimic" a cookie with a known `userId` it means that you need to be able to encrypt the token with the private key available to the server, otherwise you can't "mimic" a cookie as it's not clear text but it's encrypted.

Potentially you could have an issue if you use 2 different providers like GitHub and GitLab, I create a username `test_user_1` on GitHub and you create `test_user_1` on GitLab, then in next-auth if you use `test_user_1` as `userId` property, you can login pretending to be me by logging in with GItLab as we would both be identified by `userId: test_user_1`
This is simply prevented by using a key like `provider:userId` so they would be `github:test_user_1` and `gitlab:test_user_1`

**Comment by orangecoloured** [comment]
> it means that you need to be able to encrypt the token with the private key available to the server, otherwise you can't "mimic" a cookie as it's not clear text but it's encrypted.

Ah yes, I completely forgot about this. I was thinking in a context of a plain text cookie. So I guess in a custom setup my point would be valid.
