### ISSUE TITLE
Error: Package subpath './providers/cognito' is not defined by "exports" 

### ISSUE THREAD

**Issue by iwoork** [nextauthjs/next-auth#3652]
### Description 🐜

I've followed the upgrade path to v4 and made the following changes:
- changed references from `next-auth/client` to `next-auth/react`
- Changed `Provider` to `SessionProvider`
- Changed the config to:
```
providers: [
  CognitoProvider({
    clientId: process.env.COGNITO_CLIENT_ID,
    clientSecret: process.env.COGNITO_CLIENT_SECRET,
    issuer: process.env.COGNITO_ISSUER,
  })
]
```
- Changed `[session]` references to `{data: session}`

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Install the latest next-auth
Use cognito as provider

### Screenshots / Logs 📽

<img width="982" alt="Screen Shot 2022-01-16 at 11 40 13 PM" src="https://user-images.githubusercontent.com/1687468/149709065-6da9ef07-5b3e-40be-b755-55854041bf37.png">

### Environment 🖥

  System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 844.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/auction/node_modules/.bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.0
  npmPackages:
    next: ^12.0.8 => 12.0.8
    next-auth: ^4.1.2 => 4.1.2
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Hi, I'm not able to reproduce this. Could you create a minimal reproduction?

Also, could you show the contents of your `node_modules/next-auth/package.json` (the one the error mentions)?

**Comment by reebalazs** [comment]
I have the same issue. I've just installed the package freshly for a new project. I use yarn.

The package.json contains:

```
    "./providers/*": "./providers/*.js"
```

If I add the provider manually, it works:

```
    "./providers/google": "./providers/google.js",
    "./providers/*": "./providers/*.js"
```
Apparently, the star pattern does not work?

**Comment by ItsCrotix** [comment]
I can also confirm this bug, which can also be reproduced with other providers the same way as @iwoork described in his bugreport. 

When changing the wildcard into an absolute path it seems to work:
```
// Default
"./providers/*": "./providers/*.js"

// Fix
".providers/spotify": "./providers/spotify.js",
```

Could a workaround be to import all providers with their absolute paths?
As stated by @reebalazs , The wildcard import seems to be the issue.

### Env: 
System: Windows 11
Node: v12.18.1 
npm: 6.14.5

npmPackages:
"next": "latest",
"next-auth": "^4.0.0-beta.7",
"react": "^17.0.2",
 "react-dom": "^17.0.2"

**Comment by iwoork** [comment]
Contents of package.json from the next-auth folder:

**Comment by balazsorban44** [comment]
@iwoork where are does those `_` fields coming from? :thinking: This is how the `package.json` should look like: https://unpkg.com/browse/next-auth@4.1.2/package.json

@reebalazs This should be allowed https://nodejs.org/api/packages.html#subpath-patterns

Might be an issue with Yarn 2. I have generally bad experience with both Yarn 2 and above. If this turns out to be a related issue, I'm inclined to not spend time on it.

**Comment by reebalazs** [comment]
@balazsorban44 thank you, this is actually related to the node version. Although I am using v14, the shell that I was testing from fell back to v12  by mistake. v14 has no problems with the subpath patterns.

So luckily this is not yarn2 specific. (Since NextJS and Vercel supports yarn2 at least in node_modules mode, there is no reason for next-auth to fail.)

Any other reporter can you please confirm that the problem goes away with Node >= v14?

**Comment by iwoork** [comment]
Thanks all. I'm on v14.5.0 and yet having the issue.

**Comment by reebalazs** [comment]
@iwoork Subpath patterns
Added in: v14.13.0, v12.20.0

Upgrade!

Reference: https://nodejs.org/api/packages.html#subpath-patterns

**Comment by balazsorban44** [comment]
@iwoork https://github.com/nextauthjs/next-auth/issues/3652#issuecomment-1015026217

> Update: @iwoork could you update your Node. js version to at least 14.13.0? it seems to be the issue.

**Comment by balazsorban44** [comment]
I'm going to close this assuming the issue is resolved with the suggested update.

Note that upgrading Node 14.5.0 to at least 14.13.0 is not a breaking change and should be safe to do.

**Comment by vishalrathod8373** [comment]
I was facing this issue. I was using the **"next-auth": "^4.18.7"** version. my node version was **14.0.0**. when I update this version to **18.12.1** then the issue is resolved.

**Comment by teddybee** [comment]
I still have this issue with ts-node,
"@auth/core": "^0.8.2",
"@types/node": "^18.16.16",

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './providers/google' is not defined by "exports" in D:\...\node_modules\@auth\core\package.json
