### ISSUE TITLE
Invalid `p.account.findUnique()` invocation with prisma

### ISSUE THREAD

**Issue by MattA-Official** [nextauthjs/next-auth#3815]
### Title

Invalid `p.account.findUnique()` invocation with prisma

### How to reproduce ☕️

next-auth: `4.0.0-beta.7`
@next-auth/prisma-adapter: `0.5.2-next.19`

/pages/api/[...nextauth].ts
```ts
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { hasBetaAccess } from 'lib/backend-utils';
import { prisma } from 'lib/prisma';
import NextAuth from 'next-auth';
import Discord from 'next-auth/providers/discord';

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    Discord({
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      authorization: 'https://discord.com/api/oauth2/authorize?scope=identify+guilds',
      profile(profile) {
        let image_url: string;

        if (profile.avatar === null) {
          const defaultAvatarNumber = parseInt(profile.discriminator, 10) % 5;
          image_url = `https://cdn.discordapp.com/embed/avatars/${defaultAvatarNumber}.png`;
        } else {
          const format = profile.avatar.startsWith('a_') ? 'gif' : 'png';
          image_url = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.${format}`;
        }

        return {
          id: profile.id,
          username: profile.username,
          discriminator: profile.discriminator,
          avatar: image_url,
          profile: {
            vanity: profile.id,
            user_id: profile.id,
          },
        };
      },
    }),
  ],
  callbacks: {
    async session({ session, user }) {
      return {
        ...session,
        user,
      };
    },
    async signIn({ user }) {
      // Check for a development environment
      if (process.env.NODE_ENV === 'development') return true;

      // Check if the user has access to the beta
      const betaUser = user.beta || (await hasBetaAccess(user.id));
      return betaUser ? true : '/?error=AccessDenied';
    },
  },
});
```

Account schema
```prisma
model Account {
  id                 String  @id @default(cuid()) @map("_id")
  userId             String  @map("user_id")
  type               String
  provider           String
  providerAccountId  String  @map("provider_account_id")
  refresh_token      String?
  access_token       String?
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("accounts")
}
```

### Your question/bug report 📓

The bug below results from the above code. It is worth noting I am using **MongoDB** and not any sort of SQL.

```
Invalid `p.account.findUnique()` invocation in
C:\Users\folder\path\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique({
           where: {
             provider_providerAccountId: {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~
               providerAccountId: '366652352125599744',
               provider: 'discord'
             }
           },
           select: {
             user: true
           }
         })

Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
}
```

### Contributing  🙌🏽

Yes, I am

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by ChrisB007** [comment]
Hello all,  I was wondering if this issue has been resolved. I am experiencing a similar issue:
```
Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean `providerId_providerAccountId`? Available args:
type AccountWhereUniqueInput {
  id?: String
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}

 Error: 
Invalid `p.account.findUnique()` invocation in
/Users/blkboxng/Desktop/publicTradesProperties/Prod-tuberDome/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique({
           where: {
             provider_providerAccountId: {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~
               providerAccountId: '108759031429510900958',
               provider: 'google'
             }
           },
           select: {
             user: true
           }
         })

Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean `providerId_providerAccountId`? Available args:
type AccountWhereUniqueInput {
  id?: String
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}
```
Please advice

**Comment by ndom91** [comment]
> Hello all,  I was wondering if this issue has been resolved. I am experiencing a similar issue:
> ```
> Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean `providerId_providerAccountId`? Available args:
> type AccountWhereUniqueInput {
>   id?: String
>   providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
> }
> 
>  Error: 
> Invalid `p.account.findUnique()` invocation in
> /Users/blkboxng/Desktop/publicTradesProperties/Prod-tuberDome/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45
> 
>    8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
>    9 async getUserByAccount(provider_providerAccountId) {
>   10     var _a;
> → 11     const account = await p.account.findUnique({
>            where: {
>              provider_providerAccountId: {
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~
>                providerAccountId: '108759031429510900958',
>                provider: 'google'
>              }
>            },
>            select: {
>              user: true
>            }
>          })
> 
> Unknown arg `provider_providerAccountId` in where.provider_providerAccountId for type AccountWhereUniqueInput. Did you mean `providerId_providerAccountId`? Available args:
> type AccountWhereUniqueInput {
>   id?: String
>   providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
> }
> ```
> Please advice

It looks like you just have a small typo. `provider_ providerAccountId` should be `providerId_providerAccountId`.

**Comment by johnstjoe** [comment]
I had this problem and resolved it by directly naming the unique constraint in the Account model:

```
model Account {
  //...
  @@unique([provider, providerAccountId], name: "provider_providerAccountId")
}
```

**Comment by ImValerio** [comment]
Similar issue with MySQL
```
message: "Cannot read property 'findUnique' of undefined",
  stack: "TypeError: Cannot read property 'findUnique' of undefined\n" +
    '    at getUserByAccount (.....\\node_modules\\@next-auth\\prisma-adapter\\dist\\index.js:12:45)

Essentially in the prisma adapter p.account is undefined for some reason

This is the schema


```

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

```

Any idea?

**Comment by ndom91** [comment]
> Similar issue with MySQL
> 
> ```
> message: "Cannot read property 'findUnique' of undefined",
>   stack: "TypeError: Cannot read property 'findUnique' of undefined\n" +
>     '    at getUserByAccount (.....\\node_modules\\@next-auth\\prisma-adapter\\dist\\index.js:12:45)
> ```
> 
> ...
>  
> And this is the [...nextauth].js config
> 
> ```
> import NextAuth from "next-auth/next";
> import GithubProvider from "next-auth/providers/github"
> import { PrismaAdapter } from "@next-auth/prisma-adapter";
> import { PrismaClient } from "@prisma/client"
> 
> const prisma = new PrismaClient()
> 
> 
> export default NextAuth({
>     adapter: PrismaAdapter({ prisma }),
>     providers: [
>         GithubProvider({
>             clientId: process.env.GITHUB_ID,
>             clientSecret: process.env.GITHUB_SECRET
>         })
>     ],
>     secret: process.env.SECRET
> })
> ```
> 
> Any idea?

Hey so one small thing I noticed, the `prisma` client instance should be passed to the adapter directly as the first argument, not in an object. i.e.

```
... 
adapter: PrismaAdapter(prisma)
...
```

**Comment by ImValerio** [comment]
> > Similar issue with MySQL
> > ```
> > message: "Cannot read property 'findUnique' of undefined",
> >   stack: "TypeError: Cannot read property 'findUnique' of undefined\n" +
> >     '    at getUserByAccount (.....\\node_modules\\@next-auth\\prisma-adapter\\dist\\index.js:12:45)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> > And this is the [...nextauth].js config
> > ```
> > import NextAuth from "next-auth/next";
> > import GithubProvider from "next-auth/providers/github"
> > import { PrismaAdapter } from "@next-auth/prisma-adapter";
> > import { PrismaClient } from "@prisma/client"
> > 
> > const prisma = new PrismaClient()
> > 
> > 
> > export default NextAuth({
> >     adapter: PrismaAdapter({ prisma }),
> >     providers: [
> >         GithubProvider({
> >             clientId: process.env.GITHUB_ID,
> >             clientSecret: process.env.GITHUB_SECRET
> >         })
> >     ],
> >     secret: process.env.SECRET
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any idea?
> 
> Hey so one small thing I noticed, the `prisma` client instance should be passed to the adapter directly as the first argument, not in an object. i.e.
> 
> ```
> adapter: PrismaAdapter(prisma)
> ```

I feel so dumb, you are right now all work fine!

**Comment by ilyandho** [comment]
I had the same issue but I had forgotten to run `npx prisma migrate dev --name init` after which everything ran well.

**Comment by emmalegend** [comment]
Hi good morning, still having this same issue..

**Comment by bassem97** [comment]
hello, i have the same problem too !!! 
HELLP !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by krishnaUIDev** [comment]
> hello, i have the same problem too !!! HELLP !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Try this ``npx prisma migrate dev --name init``

**Comment by bassem97** [comment]
> 
> 
> 
> > hello, i have the same problem too !!! HELLP !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Try this ``npx prisma migrate dev --name init``

I tried many times, the problem still persist

**Comment by bassem97** [comment]
problem solved by modifying  prisma schema to this: 

```prisma

model User {
  id                    String     @id @default(uuid())
  name                  String
  email                 String?    @unique
  emailVerified         DateTime?   @map("email_verified")
  image                 String?
  createdAt             DateTime   @default(now())
  updatedAt             DateTime   @updatedAt
  accounts              Account[]
  sessions              Session[]
  @@map("users")
}
model Account {
  id                 String    @id @default(cuid())
  userId              String    @map("user_id")
  type                 String?
  provider           String
  providerAccountId  String    @map("provider_account_id")
  token_type         String?
  refresh_token      String?   @db.Text
  access_token       String?   @db.Text
  expires_at         Int?
  scope              String?
  id_token           String? @db.Text
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("accounts")
}

model Session {
  id           String   @id @default(cuid())
  userId       String?  @map("user_id")
  sessionToken String   @db.Text @map("session_token") @unique
  accessToken  String?  @db.Text @map("access_token")
  expires      DateTime
  user         User?     @relation(fields: [userId], references: [id], onDelete: Cascade)
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt

  @@map("sessions")
}

model VerificationRequest {
  id         String   @id @default(cuid())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@unique([identifier, token])
}
```
then execute npx prisma db push to apply schema changes to remote db

**Comment by ethanniser** [comment]
This fixed for me (using google oauth + planetscale mysql) thanks

**Comment by ignaprados** [comment]
Thanks @bassem97, it works!!

**Comment by bassem97** [comment]
> Thanks @bassem97, it works!!
> 

Glad to hear 😍

**Comment by payamsaremi** [comment]
I'm having a similar problem here.
I deleted a user from Prisma studio and after that when I try to create a new user I get this error.
nextjs, prisma, planetscale, nextauth.

`[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser 
Invalid `p.user.create()` invocation in
/Users/lantos/Desktop/Geno-landing/node_modules/@next-auth/prisma-adapter/dist/index.js:6:38

  3 exports.PrismaAdapter = void 0;
  4 function PrismaAdapter(p) {
  5     return {
→ 6         createUser: (data) => p.user.create(
Unique constraint failed on the (not available) {
  message: '\n' +
    'Invalid `p.user.create()` invocation in\n' +
    '/Users/lantos/Desktop/Geno-landing/node_modules/@next-auth/prisma-adapter/dist/index.js:6:38\n' +
    '\n' +
    '  3 exports.PrismaAdapter = void 0;\n' +
    '  4 function PrismaAdapter(p) {\n' +
    '  5     return {\n' +
    '→ 6         createUser: (data) => p.user.create(\n' +
    'Unique constraint failed on the (not available)',
  stack: 'Error: \n' +
    'Invalid `p.user.create()` invocation in\n' +
    '/Users/lantos/Desktop/Geno-landing/node_modules/@next-auth/prisma-adapter/dist/index.js:6:38\n' +
    '\n' +
    '  3 exports.PrismaAdapter = void 0;\n' +
    '  4 function PrismaAdapter(p) {\n' +
    '  5     return {\n' +
    '→ 6         createUser: (data) => p.user.create(\n' +
    'Unique constraint failed on the (not available)\n' +
    '    at RequestHandler.handleRequestError (/Users/lantos/Desktop/Geno-landing/node_modules/@prisma/client/runtime/index.js:35024:13)\n' +
    '    at RequestHandler.handleAndLogRequestError (/Users/lantos/Desktop/Geno-landing/node_modules/@prisma/client/runtime/index.js:34996:12)\n' +
    '    at RequestHandler.request (/Users/lantos/Desktop/Geno-landing/node_modules/@prisma/client/runtime/index.js:34991:12)\n' +
    '    at async PrismaClient._request (/Users/lantos/Desktop/Geno-landing/node_modules/@prisma/client/runtime/index.js:36082:16)',
  name: 'Error'
}
`

**Comment by payamsaremi** [comment]
I have tried your solution but I get this error, and I need my user.
will tis really drop the User table? or it's a false message?

You are about to drop the `User` table, which is not empty (11 rows).

**Comment by payamsaremi** [comment]
@bassem97  I have tried your solution but I get this error, and I need my user.
will tis really drop the User table? or it's a false message?

You are about to drop the User table, which is not empty (11 rows).

**Comment by frank1003A** [comment]
@emmalegend were you able to resolve this ?

> Hi good morning, still having this same issue..
> 
> //schema.prisma
> 
> ```
> datasource db {
>   provider = "mongodb"
>   url      = env("MONGODB_URI")
> }
> 
> generator client {
>   provider        = "prisma-client-js"
> 
> }
> 
> model Account {
>   id  String  @id @default(auto()) @map("_id") @db.ObjectId
>   userId             String 
>   type               String
>   provider           String
>   providerAccountId  String
>   refresh_token      String?  @db.String
>   access_token       String?  @db.String
>   expires_at         Int?
>   token_type         String?
>   scope              String?
>   id_token           String?  @db.String
>   session_state      String?
> 
>   user User @relation(fields: [userId], references: [id], onDelete: Cascade)
> 
>   @@unique([provider, providerAccountId])
> }
> 
> model Session {
>   id  String  @id @default(auto()) @map("_id") @db.ObjectId
>   sessionToken String   @unique
>   userId       String
>   expires      DateTime
>   user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
> }
> 
> model User {
>   id  String  @id @default(auto()) @map("_id") @db.ObjectId
>   name          String?
>   email         String?   @unique
>   emailVerified DateTime?
>   image         String?
>   accounts      Account[]
>   sessions      Session[]
> }
> 
> model VerificationToken {
>     id  String  @id @default(auto()) @map("_id") @db.ObjectId
>   identifier String
>   token      String   @unique
>   expires    DateTime
> 
>   @@unique([identifier, token])
> }
> ```
> 
> //[...nextauth].ts
> 
> ```
> import NextAuth from "next-auth";
> import GoogleProvider from "next-auth/providers/google";
> import { PrismaAdapter } from "@next-auth/prisma-adapter";
> import { PrismaClient } from "@prisma/client";
> 
> const prisma = new PrismaClient();
> 
> export default NextAuth({
>   adapter: PrismaAdapter(prisma),
>   providers: [
>     GoogleProvider({
>       clientId: process.env.GOOGLE_CLIENT_ID as string,
>       clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
>     }),
>   ],
>   secret: process.env.NEXTAUTH_SECRET,
> });
> ```
> 
> //Error
> 
> ```
> [next-auth][error][adapter_error_getUserByAccount] 
> https://next-auth.js.org/errors#adapter_error_getuserbyaccount 
> Invalid `p.account.findUnique()` invocation in
> /Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45
> 
>    8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
>    9 async getUserByAccount(provider_providerAccountId) {
>   10     var _a;
> → 11     const account = await p.account.findUnique(
> Raw query failed. Code: `unknown`. Message: `Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-nymnfql-shard-00-02.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-01.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-00.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }` {
>   message: '\n' +
>     'Invalid `p.account.findUnique()` invocation in\n' +
>     '/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
>     '\n' +
>     '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
>     '   9 async getUserByAccount(provider_providerAccountId) {\n' +
>     '  10     var _a;\n' +
>     '→ 11     const account = await p.account.findUnique(\n' +
>     'Raw query failed. Code: `unknown`. Message: `Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-nymnfql-shard-00-02.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-01.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-00.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }`',
>   stack: 'Error: \n' +
>     'Invalid `p.account.findUnique()` invocation in\n' +
>     '/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45\n' +
>     '\n' +
>     '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
>     '   9 async getUserByAccount(provider_providerAccountId) {\n' +
>     '  10     var _a;\n' +
>     '→ 11     const account = await p.account.findUnique(\n' +
>     'Raw query failed. Code: `unknown`. Message: `Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-nymnfql-shard-00-02.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-01.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-00.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }`\n' +
>     '    at RequestHandler.handleRequestError (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:31955:13)\n' +
>     '    at RequestHandler.handleAndLogRequestError (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:31913:12)\n' +
>     '    at /Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:32458:25\n' +
>     '    at async PrismaClient._executeRequest (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:33022:22)\n' +
>     '    at async PrismaClient._request (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:32994:16)\n' +
>     '    at async getUserByAccount (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29)',
>   name: 'Error'
> }
> [next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
> https://next-auth.js.org/errors#oauth_callback_handler_error 
> Invalid `p.account.findUnique()` invocation in
> /Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45
> 
>    8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
>    9 async getUserByAccount(provider_providerAccountId) {
>   10     var _a;
> → 11     const account = await p.account.findUnique(
> Raw query failed. Code: `unknown`. Message: `Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-nymnfql-shard-00-02.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-01.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-00.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }` Error: 
> Invalid `p.account.findUnique()` invocation in
> /Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45
> 
>    8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
>    9 async getUserByAccount(provider_providerAccountId) {
>   10     var _a;
> → 11     const account = await p.account.findUnique(
> Raw query failed. Code: `unknown`. Message: `Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-nymnfql-shard-00-02.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-01.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: ac-nymnfql-shard-00-00.k1eh2av.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }`
>     at RequestHandler.handleRequestError (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:31955:13)
>     at RequestHandler.handleAndLogRequestError (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:31913:12)
>     at /Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:32458:25
>     at async PrismaClient._executeRequest (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:33022:22)
>     at async PrismaClient._request (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@prisma/client/runtime/index.js:32994:16)
>     at async getUserByAccount (/Users/macintoshhd/Desktop/MERN/nextjs/imessage/frontend/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29) {
>   name: 'GetUserByAccountError',
>   code: undefined
> }
> ```
> 
> Please help

**Comment by mcnaveen** [comment]
All of a sudden, I'm facing the same issue. Not sure how to solve it. I'm using Google, and Email Magic Link login.

**Comment by frank1003A** [comment]
> Everything was working fine. All of a sudden, I'm facing the same issue. Not sure how to solve it. I'm using Google, and Email Magic Link login.

Found out that this issue is related to [#2803｜Linking accounts](https://github.com/nextauthjs/next-auth/issues/2803).

**Comment by imrookhan44** [comment]
Error: P1001: Can't reach database server at `ep-cool-fire-634750.us-east-2.aws.neon.tech`:`5432`

**Comment by bassem97** [comment]
> Thanks @bassem97, it works!

just save you user and press Y

**Comment by CloudCodesStuff** [comment]
@bassem97  im stilling getting an error with your schema, it says 
`Error: foreign key constraints are not allowed, see https://vitess.io/blog/2021-06-15-online-ddl-why-no-fk/
   0: sql_schema_connector::apply_migration::migration_step
           with step=AddForeignKey { foreign_key_id: ForeignKeyId(0) }
             at schema-engine\connectors\sql-schema-connector\src\apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine\connectors\sql-schema-connector\src\apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine\core\src\state.rs:441`

**Comment by itsjavi** [comment]
TL;DR;

I had this issue when using prisma + neon postgresql DB
the problem was in my schema. I fixed it after changing the User email from this:

```prisma
email            String?           @unique @db.VarChar(255)
```

to this:

```prisma
email            String?           @unique
```

Now the column is of type `text` instead of `varchar`. It seems it had issues with that.

**Comment by iiiok** [comment]
Try run [npx prisma db push] to test Ur Prisma connect first.
If Ur Prisma returns DNS error:[An error occured during DN5 resolution: no record found for name]
then, it is a firewall issue.
It cost me days to figure that out.

**Comment by currenthandle** [comment]
> problem solved by modifying prisma schema to this:
> 
> ```prisma
> model User {
>   id                    String     @id @default(uuid())
>   name                  String
>   email                 String?    @unique
>   emailVerified         DateTime?   @map("email_verified")
>   image                 String?
>   createdAt             DateTime   @default(now())
>   updatedAt             DateTime   @updatedAt
>   accounts              Account[]
>   sessions              Session[]
>   @@map("users")
> }
> model Account {
>   id                 String    @id @default(cuid())
>   userId              String    @map("user_id")
>   type                 String?
>   provider           String
>   providerAccountId  String    @map("provider_account_id")
>   token_type         String?
>   refresh_token      String?   @db.Text
>   access_token       String?   @db.Text
>   expires_at         Int?
>   scope              String?
>   id_token           String? @db.Text
>   createdAt          DateTime  @default(now())
>   updatedAt          DateTime  @updatedAt
>   user               User      @relation(fields: [userId], references: [id], onDelete: Cascade)
> 
>   @@unique([provider, providerAccountId])
>   @@map("accounts")
> }
> 
> model Session {
>   id           String   @id @default(cuid())
>   userId       String?  @map("user_id")
>   sessionToken String   @db.Text @map("session_token") @unique
>   accessToken  String?  @db.Text @map("access_token")
>   expires      DateTime
>   user         User?     @relation(fields: [userId], references: [id], onDelete: Cascade)
>   createdAt    DateTime @default(now())
>   updatedAt    DateTime @updatedAt
> 
>   @@map("sessions")
> }
> 
> model VerificationRequest {
>   id         String   @id @default(cuid())
>   identifier String
>   token      String   @unique
>   expires    DateTime
>   createdAt  DateTime @default(now())
>   updatedAt  DateTime @updatedAt
> 
>   @@unique([identifier, token])
> }
> ```
> 
> then execute npx prisma db push to apply schema changes to remote db

This seems to work for me as well! Thanks a lot 🙏 

Can you please provide some more context as to what you did and why this works? Specifically, why does this `schema.prisma` work and the implementation provided in the official documentation does not? https://authjs.dev/reference/adapter/prisma

Thank you!

**Comment by bassem97** [comment]
> This seems to work for me as well! Thanks a lot 🙏
> 
> @bassem97 can you please provide some more context as to what you did and why/how this resolves the issue? Specifically, why does this `schema.prisma` (the one your provided) work and the implementation provided in the official documentation does not? https://authjs.dev/reference/adapter/prisma
> 
> Thank you!
> 
> > problem solved by modifying prisma schema to this:
> > ```prisma
> > model User {
> >   id                    String     @id @default(uuid())
> >   name                  String
> >   email                 String?    @unique
> >   emailVerified         DateTime?   @map("email_verified")
> >   image                 String?
> >   createdAt             DateTime   @default(now())
> >   updatedAt             DateTime   @updatedAt
> >   accounts              Account[]
> >   sessions              Session[]
> >   @@map("users")
> > }
> > model Account {
> >   id                 String    @id @default(cuid())
> >   userId              String    @map("user_id")
> >   type                 String?
> >   provider           String
> >   providerAccountId  String    @map("provider_account_id")
> >   token_type         String?
> >   refresh_token      String?   @db.Text
> >   access_token       String?   @db.Text
> >   expires_at         Int?
> >   scope              String?
> >   id_token           String? @db.Text
> >   createdAt          DateTime  @default(now())
> >   updatedAt          DateTime  @updatedAt
> >   user               User      @relation(fields: [userId], references: [id], onDelete: Cascade)
> > 
> >   @@unique([provider, providerAccountId])
> >   @@map("accounts")
> > }
> > 
> > model Session {
> >   id           String   @id @default(cuid())
> >   userId       String?  @map("user_id")
> >   sessionToken String   @db.Text @map("session_token") @unique
> >   accessToken  String?  @db.Text @map("access_token")
> >   expires      DateTime
> >   user         User?     @relation(fields: [userId], references: [id], onDelete: Cascade)
> >   createdAt    DateTime @default(now())
> >   updatedAt    DateTime @updatedAt
> > 
> >   @@map("sessions")
> > }
> > 
> > model VerificationRequest {
> >   id         String   @id @default(cuid())
> >   identifier String
> >   token      String   @unique
> >   expires    DateTime
> >   createdAt  DateTime @default(now())
> >   updatedAt  DateTime @updatedAt
> > 
> >   @@unique([identifier, token])
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then execute npx prisma db push to apply schema changes to remote db

I dunno why the NextAuth documentation isn't updated , but it seems like next team forgot to apply the new prisma rules or something, like the attribut providerAccountId  in Account table should be mapped in the db like this "provided_account_id" and the sessionToken and so on, hope they fix it asap

**Comment by currenthandle** [comment]
@bassem97 I'm happy to make a PR to the next-auth docs, unless you want to do it, lmk: https://github.com/nextauthjs/next-auth/blob/d73812bce5f5dc2f3f8b839554fc66a41284be30/packages/adapter-prisma/src/index.ts#L77

I'm curious though if not the docs, where did you find or how did you work out this alternate (and functional) implementation? Obviously, you are correct, because your code works 😊 But I'm curious how/where you found this eg: "attribut providerAccountId in Account table should be mapped in the db like this "provided_account_id" and the sessionToken and so on" if not in the docs.

Thanks again!

**Comment by bassem97** [comment]
> @bassem97 I'm happy to make a PR to the next-auth docs, unless you want to do it, lmk: https://github.com/nextauthjs/next-auth/blob/d73812bce5f5dc2f3f8b839554fc66a41284be30/packages/adapter-prisma/src/index.ts#L45
> 
> I'm curious though if not the docs, where did you find or how did you work out this alternate (and functional) implementation? Obviously, you are correct, because your code works 😊 But I'm curious how/where you found this eg: "attribut providerAccountId in Account table should be mapped in the db like this "provided_account_id" and the sessionToken and so on" if not in the docs.
> 
> Thanks again!

Yes please, let me do you.
Actually i found it on my own, it took me barely 2 days of debugging and investigating about the real source of the error, and here we are, and you'r welcome man

**Comment by currenthandle** [comment]
@bassem97 Will do. When you say you "found it on [your] own." Where did you find it? I imagine not just trial and error lol. Curious what resources your looking at. Maybe I can learn something from your process  💪

**Comment by bassem97** [comment]
> @bassem97 Will do. When you say you "found it on [your] own." Where did you find it? I imagine not just trial and error lol. Curious what resources your looking at. Maybe I can learn something from your process  💪

When i said "found it on my own " i mean that i didn't found it on google or smthg , to simplify the process i can say that the final schema i got it after  many tentatives, every time i change a value and see what the output/error  and so on, i you wanna talk about it you can dm me on one of my socials in my github profile

**Comment by sonipranjal** [comment]
Thanks, @bassem97, Your solution works! 

It took almost one year to find the solution to this issue lol

**Comment by bassem97** [comment]
@sonipranjal  glad to hear this 🙏🥳

**Comment by atlas700** [comment]
> @bassem97  Tnx man!

**Comment by bassem97** [comment]
> > @bassem97  Tnx man!
> 
> 

You're welcome !!

**Comment by pedrolucasfv** [comment]
> You're welcome !!

YOU ARE GOD MY FRIEND, I FIXED MY PROBLEM WITH THIS CODE, BEAUTIFUL, PERFECT, THE BEST!!!!!!!!!!!!!!

**Comment by Zeyu-Li** [comment]
I still get issues sometimes, what is the exact issue with this?

**Comment by bassem97** [comment]
> > You're welcome !!
> 
> YOU ARE GOD MY FRIEND, I FIXED MY PROBLEM WITH THIS CODE, BEAUTIFUL, PERFECT, THE BEST!!!!!!!!!!!!!!

Glad it worked !!!!!! you're welcome

**Comment by pksingh-sme** [comment]
Add "@map("provider_account_id")" in model Account for field

providerAccountId  String @map("provider_account_id")

**Comment by bassem97** [comment]
> > problem solved by modifying prisma schema to this:
> > ```prisma
> > model User {
> >   id                    String     @id @default(uuid())
> >   name                  String
> >   email                 String?    @unique
> >   emailVerified         DateTime?   @map("email_verified")
> >   image                 String?
> >   createdAt             DateTime   @default(now())
> >   updatedAt             DateTime   @updatedAt
> >   accounts              Account[]
> >   sessions              Session[]
> >   @@map("users")
> > }
> > model Account {
> >   id                 String    @id @default(cuid())
> >   userId              String    @map("user_id")
> >   type                 String?
> >   provider           String
> >   providerAccountId  String    @map("provider_account_id")
> >   token_type         String?
> >   refresh_token      String?   @db.Text
> >   access_token       String?   @db.Text
> >   expires_at         Int?
> >   scope              String?
> >   id_token           String? @db.Text
> >   createdAt          DateTime  @default(now())
> >   updatedAt          DateTime  @updatedAt
> >   user               User      @relation(fields: [userId], references: [id], onDelete: Cascade)
> > 
> >   @@unique([provider, providerAccountId])
> >   @@map("accounts")
> > }
> > 
> > model Session {
> >   id           String   @id @default(cuid())
> >   userId       String?  @map("user_id")
> >   sessionToken String   @db.Text @map("session_token") @unique
> >   accessToken  String?  @db.Text @map("access_token")
> >   expires      DateTime
> >   user         User?     @relation(fields: [userId], references: [id], onDelete: Cascade)
> >   createdAt    DateTime @default(now())
> >   updatedAt    DateTime @updatedAt
> > 
> >   @@map("sessions")
> > }
> > 
> > model VerificationRequest {
> >   id         String   @id @default(cuid())
> >   identifier String
> >   token      String   @unique
> >   expires    DateTime
> >   createdAt  DateTime @default(now())
> >   updatedAt  DateTime @updatedAt
> > 
> >   @@unique([identifier, token])
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then execute npx prisma db push to apply schema changes to remote db
> 
> bro THANK YOU!!!!!!!

@samgable27 you're welcome 🎆

**Comment by janusqa** [comment]
```sessionToken String   @unique @map("session_token") @db.Text```
This line is producing the following error
```
Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Native type `Text` cannot be unique in MySQL. Please use the `length` argument to the field in the index definition to allow this.
```

**Comment by bassem97** [comment]
> `sessionToken String @unique @map("session_token") @db.Text` This line is producing the following error
> 
> ```
> Error: Prisma schema validation - (validate wasm)
> Error code: P1012
> error: Native type `Text` cannot be unique in MySQL. Please use the `length` argument to the field in the index definition to allow this.
> ```

@janusqa can you first inverse the order of @db.text and @unique , then verify Prisma version:
`sessionToken String   @db.Text @map("session_token") @unique`

**Comment by janusqa** [comment]
> > `sessionToken String @unique @map("session_token") @db.Text` This line is producing the following error
> > ```
> > Error: Prisma schema validation - (validate wasm)
> > Error code: P1012
> > error: Native type `Text` cannot be unique in MySQL. Please use the `length` argument to the field in the index definition to allow this.
> > ```
> 
> @janusqa can you first inverse the order of @db.text and @unique , then verify Prisma version: `sessionToken String @db.Text @map("session_token") @unique`

@bassem97 
```
"@prisma/client": "^5.3.1",
"prisma": "^5.3.1",
```
Saving the schema file automatically inverted the order for me already.

**Comment by bassem97** [comment]
> "prisma":

@janusqa can you please switch to v5.2.0 and see if the problem persist ?

**Comment by bassem97** [comment]
> @bassem97 It's still there in 5.2.0 as far as I see. Note to make the error go away I have just dropped the @db.Text Maybe this is unique to mySql
> 
> I found this [prisma/prisma#8661](https://github.com/prisma/prisma/issues/8661) It makes sense to me too to change the db.Text to db.varchar()
> 
> ```
>   sessionToken String   @unique @map("session_token") @db.VarChar(191)
> ```
> 
> and specify the max length of what the session token should be like 191

@janusqa i would recommend doing that if i knew that you are using MySQL and not Postgres, glad it worked anyways !

**Comment by utkarshkhanna2609** [comment]
next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `prisma.account.findUnique()` invocation:


error: Error validating datasource `db`: the URL must start with the protocol `mysql://`.
  -->  schema.prisma:7
   | 
 6 |   provider     = "mysql"
 7 |   url          = env("DATABASE_URL")
   | 

Validation Error Count: 1 PrismaClientInitializationError: 
Invalid `prisma.account.findUnique()` invocation:


error: Error validating datasource `db`: the URL must start with the protocol `mysql://`.
  -->  schema.prisma:7
   | 
 6 |   provider     = "mysql"
 7 |   url          = env("DATABASE_URL")
   | 

Validation Error Count: 1
  name: 'GetUserByAccountError',
  code: undefined
}

I was facing this issue too, turns out, the environment variable of my planetscale db url was incorrect, hope this helps!

**Comment by devwax** [comment]
Regenerating the Prisma client fixed it for me.

`npx prisma generate`

I had been working with and merging an older branch of the app. That may have caused it. 

I had also run `npm run build` a few times recently while troubleshooting deployment errors locally. Not sure if that can necessitate a prisma client rebuild. Anyway, I would definitely try it. An easy fix for a perplexing problem.

**Comment by jahangeer7704** [comment]
model Account {
id String @id @default(auto()) @Map("_id") @db.ObjectId
userId String @db.ObjectId
type String?
provider String?
providerAccountId String?
refresh_token String? @db.String
access_token String? @db.String
expires_at Int?
token_type String?
scope String?
id_token String? @db.String
session_state String?

createdAt DateTime @default(now())
updatedAt DateTime @updatedAt

user User @relation(fields: [userId], references: [id], onDelete: Cascade)

@https://github.com/unique([provider, providerAccountId])
} i made my model like this ,the issue gone

**Comment by SavixDR** [comment]
@bassem97 Thanks brother. ❤️ you're a lifesaver ❤️‍🔥

**Comment by congduong97** [comment]
> @Zeyu-Li
> 
> ```
> Account
>   provider           String
>   providerAccountId  String    @map("provider_account_id")
>   
>   @@unique([provider, providerAccountId])
> ```
> 
> This part is what solves the issue. This mapping is needed to resolve the issue

It works for me,Thanks
