### ISSUE TITLE
npm WARN EBADENGINE Unsupported engine

### ISSUE THREAD

**Issue by christianferraz** [nextauthjs/next-auth#5728]
### Environment

When installing next-auth, the following message appears below?

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openid-client@5.1.9',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v18.12.0', npm: '8.19.3' }
npm WARN EBADENGINE }

File package-lock.json
node_modules/next-auth": {
      "version": "4.15.1",
      "resolved": "https://registry.npmjs.org/next-auth/-/next-auth-4.15.1.tgz",
      "integrity": "sha512-yB/cSEqslaXAsLZ3lvkJbB7bRR5JeZvfUXSw0CmWeP+TaMZWB85fG9PWdfBeFrDCLBsoyATw9FF6fzApE0SxSw==",
      "dependencies": {
        "@babel/runtime": "^7.16.3",
        "@panva/hkdf": "^1.0.1",
        "cookie": "^0.5.0",
        "jose": "^4.9.3",
        "oauth": "^0.9.15",
        "openid-client": "^5.1.0",
        "preact": "^10.6.3",
        "preact-render-to-string": "^5.1.19",
        "uuid": "^8.3.2"
      },

### Reproduction URL

project it's private

### Describe the issue

When installing next-auth, the following message appears warning

### How to reproduce

npm i next-auth

### Expected behavior

No warn message

**Comment by KloudJack** [comment]
Duplicate of #4575

**Comment by balazsorban44** [comment]
Fixed in `4.15.1` and newer, please upgrade: https://github.com/nextauthjs/next-auth/releases/tag/next-auth%40v4.15.1

**Comment by Kfelts** [comment]
This wasn't fixed in the release. I upgraded to both 4.15.1 and 4.15.2 and the error remained. It specifies the node engine as `{"node":"^12.19.0 || ^14.15.0 || ^16.13.0 || ^18.12.0"}`
I have 18.6.0 installed. I ended up having to remove NextAuth from my project to get the package.json to run without issue.

`npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: next-auth@4.15.2
npm ERR! notsup Not compatible with your version of node/npm: next-auth@4.15.2
npm ERR! notsup Required: {"node":"^12.19.0 || ^14.15.0 || ^16.13.0 || ^18.12.0"}
npm ERR! notsup Actual:   {"npm":"8.13.2","node":"v18.6.0"}`

**Comment by JSRossiter** [comment]
for people still having this issue, you just need to update the version of `openid-client` you have installed to >=5.1.10. I did this by removing next-auth from package.json, `npm install` then `npm install next-auth`

**Comment by nkkky** [comment]
> for people still having this issue, you just need to update the version of `openid-client` you have installed to >=5.1.10. I did this by removing next-auth from package.json, `npm install` then `npm install next-auth`

this does not work for me. i am on node v.19.0.0/v.19.2.0, npm v9.1.2

**Comment by boyluan** [comment]
> for people still having this issue, you just need to update the version of `openid-client` you have installed to >=5.1.10. I did this by removing next-auth from package.json, `npm install` then `npm install next-auth`

this did not work for me, unfortunately.
