### ISSUE TITLE
4.18.4 no longer respects `signIn(..., {redirect: false})`

### ISSUE THREAD

**Issue by EvHaus** [nextauthjs/next-auth#6001]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 24.48 GB / 31.32 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v17.8.0/bin/npm
  npmPackages:
    next: 13.0.6 => 13.0.6
    next-auth: 4.18.0 => 4.18.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://stackblitz.com/edit/github-61ga3k-pvybxx?file=pages%2Findex.tsx,pages%2Fapi%2Fauth%2F[...nextauth].ts

### Describe the issue

After upgrading from 4.18.0 to 4.18.4 I noticed that `signIn(..., {redirect: false})` is no longer respecting the `redirect: false` option.

In my app I have a `CredentialsProvider` and I issue a signIn request like this:

```js
const result = await signIn('myapp-login', {
    {username, password},
    redirect: false,
});
```

In 4.18.0, after a successful login, it this would return:

```js
{
    error: null,
    ok: true,
    status: 200,
    url: "http://localhost:3000/login"
}
```

But in 4.18.4 it returns:

```js
{
    error: null,
    ok: false,
    status: 302,
    url: "http://localhost:3000/login"
}
```

### How to reproduce

Create an example app with `next-auth@4.18.4` and update the `signIn()` call in the header to use the `redirect: false` option. Proceed to login and check the response of the `signIn()` request.

### Expected behavior

The `signIn()` call should resolve with an `ok: true` object upon successful login.

**Comment by balazsorban44** [comment]
Identified the issue, here is an experimental release to test out: https://github.com/nextauthjs/next-auth/pull/6004#issuecomment-1344158595

**Comment by balazsorban44** [comment]
This should be fixed in `4.18.5`, please give it a try!

**Comment by mikloshumli** [comment]
I have a problem with 4.18.5 version:

development mode works fine signIn('credentials', { redirect: false, ...data })
return 
```{
    "error": "CredentialsSignin",
    "status": 200,
    "ok": true,
    "url": "https://praktiker-pwa.neoportal.hu/api/auth/signin?csrf=true"
}```

but production mode response
```
{
    "error": null,
    "status": 200,
    "ok": true,
    "url": null
}
```
This is a bug or feature?
Can you help me @balazsorban44 ?

**Comment by TerrySlack** [comment]
I'm still getting this in 4.18.7.  Reverted to 4.18.0 and the issue is still there.
However, when using 4.18.5, the error is not there.

**Comment by nmicun** [comment]
I have the same problem with @auth/core 0.2.5 in SvelteKit, redirect: false is working in dev mode, but not in production

**Comment by nmicun** [comment]
@balazsorban44  I tried with @auth/core 0.3.0 and @auth/sveltekit 0.2.0, but the same problem, redirect: false not working in production with email provider, it redirects on /auth/error/verify-request?provider=email&type=email. 

`const res = await signIn("email", {email: email, redirect: false})`

**Comment by nmicun** [comment]
sorry @balazsorban44,  any news about this? its a little bit blocking for me

**Comment by binaryme** [comment]
@nmicun I discovered the same behavior in sveltekit, but instead of removing error I opted for converting error to a boolean:
`if (redirect || !isSupportingReturn || Boolean(error)) {
        // TODO: Do not redirect for Credentials and Email providers by default in next major
        window.location.href = data.url ?? callbackUrl;
        // If url contains a hash, the browser does not reload the page. We reload manually
        if (data.url.includes("#"))
            window.location.reload();
        return;
    }`
    
I console logged the evaluated variables and discovered that if there is no error, error returns null 
`
🚀 ~ file: client.js:10 ~ signIn ~ redirect: false client.js:15 
🚀 ~ file: client.js:15 ~ signIn ~ isSupportingReturn: true client.js:38 
🚀 ~ file: client.js:37 ~ signIn ~ error: null
`

that's why removing error in your case temporarily fixed the issue.

**Comment by WolfVector** [comment]
I'm also using sveltekit, In my case I fixed it by doing

```
if ((redirect || !isSupportingReturn) && !error) {
  // TODO: Do not redirect for Credentials and Email providers by default in next major
  window.location.href = data.url ?? callbackUrl;
  // If url contains a hash, the browser does not reload the page. We reload manually
  if (data.url.includes("#")) window.location.reload();
  return;
}

res.error = error
return res
```

Just like @binaryme  said, **error** is null when the signIn is successfull and it is a string when there is an error. So in this way, the returned object will have the **error** property and you could check what value it has.
