### ISSUE TITLE
API handler should not return a value, received object. 

### ISSUE THREAD

**Issue by GhouI** [nextauthjs/next-auth#8234]
### Question 💬

Currently, I am experiencing an issue with Next-Auth. I am trying to set up a GitHub provider, but I am getting the error: ‘API handler should not return a value, received object.’ What happens is that I get redirected to the GitHub auth page. I sign in with my information. GitHub Auth sends the data back to the website (I can see this in the console), and it gives me this error below.
```console

  message: 'getUserByAccount is not a function',
  stack: 'TypeError: getUserByAccount is not a function\n' +
    '    at Object.callback (/workspaces/cloneofwebsite/node_modules/next-auth/core/routes/callback.js:83:39)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async AuthHandler (/workspaces/cloneofwebsite/node_modules/next-auth/core/index.js:208:28)\n' +
    '    at async NextAuthApiHandler (/workspaces/cloneofwebsite/node_modules/next-auth/next/index.js:22:19)\n' +
    '    at async NextAuth._args$ (/workspaces/cloneofwebsite/node_modules/next-auth/next/index.js:106:14)',
  name: 'TypeError'
API handler should not return a value, received object. 
}
```
// [pages/api/auth/[...nextauth].ts] file
```typescript
import bcrypt from "bcrypt"
import  { NextAuthOptions } from "next-auth"
import NextAuth from "next-auth/next"
import CredentialsProvider from "next-auth/providers/credentials"
import GithubProvider from "next-auth/providers/github"
import { PrismaAdapter } from "@next-auth/prisma-adapter"
import {PrismaClient} from "@prisma/client"



const prisma = new PrismaClient()
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID as string,
      clientSecret: process.env.GITHUB_SECRET as string,
    } 
    ),
    CredentialsProvider({
      name: 'credentials',
      credentials: {
        email: { label: 'email', type: 'text' },
        password: { label: 'password', type: 'password' }
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) {
          throw new Error('Invalid credentials');
        }

        const user = await prisma.user.findUnique({
          where: {
            email: credentials.email
          }
        });

        if (!user || !user?.hashedPassword) {
          throw new Error('Invalid credentials');
        }

        const isCorrectPassword = await bcrypt.compare(
          credentials.password,
          user.hashedPassword
        );

        if (!isCorrectPassword) {
          throw new Error('Invalid credentials');
        }

        return user;
      }
    })
  ],
  debug: process.env.NODE_ENV === 'development',
  secret: process.env.NEXTAUTH_SECRET,
  pages: {
    signIn: '/',
  },

}

export default NextAuth(authOptions);
```

My Current Github Settings 
![image](https://github.com/nextauthjs/next-auth/assets/23269296/f37024f0-0e9b-4e6f-9533-246a79732aaa)

### How to reproduce ☕️

1. **Setting Up GitHub Authentication for Your App**

   Begin by creating an authentication system using GitHub for your application.

2. **Configure Environment Variables**

   Open your environment (ENV) file and enter the GitHub Client ID and GitHub Secret that you obtained when you created your GitHub OAuth App.

3. **Create Authentication API Endpoint**

   Inside your project directory, create a new folder path: `pages/api/auth`.

4. **Create Authentication Configuration File**

   Within the newly created `auth` folder, generate a file named `[...nextauth].ts`.

5. **Add Authentication Configuration**

   Copy and paste the provided code snippet into the `[...nextauth].ts` file. This code contains the necessary configuration for authentication.

6. **Implement GitHub Sign-In Button**

   In your `layout.tsx` file, create a button that triggers the GitHub sign-in process. Import the required function: `import { signIn } from 'next-auth/react';`.

   ```jsx
   import { signIn } from 'next-auth/react';

   function YourLayoutComponent() {
     // ... Your layout code ...

     return (
       // ... Other components ...
       <button onClick={() => signIn('github')}>Sign in with GitHub</button>
       // ... Other components ...
     );
   }
   ```

7. **Test Your Application**

   Run your application using the command `npm run dev`. Access the page in your browser and click the "Sign in with GitHub" button you added. This will initiate the GitHub login process. After successfully logging in with your GitHub account, observe your integrated development environment (IDE) terminal for any errors.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by viethoang7276** [comment]
I have the same issue

**Comment by tszhong0411** [comment]
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(cuid())
  userId            String  @map("user_id")
  type              String
  provider          String
  providerAccountId String  @map("provider_account_id")
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique @map("session_token")
  userId       String   @map("user_id")
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  accounts      Account[]
  sessions      Session[]
  posts         Post[]
  likes         Like[]
  bio           String?
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

I got this error too. And I changed the schema to the above. It solved the problem.

**Comment by GhouI** [comment]
@tszhong0411 What did you change in your scheme?

**Comment by tszhong0411** [comment]
@GhouI I don't remember. My original one is very messy with different versions. I just copied the schema from https://authjs.dev/reference/adapter/prisma. It solved the error.

**Comment by ThangHuuVu** [comment]
Should be fixed in #8244, we'll publish a package 🔜

**Comment by GhouI** [comment]
> Should be fixed in #8244, we'll publish a package 🔜

I have stopped getting `API handler should not return a value, received object.`which is great but I am still getting the error of `getUserByAccount`. 
Do you have any suggestions on what I could do?
