### ISSUE TITLE
@auth/drizzle-adapter incompatibility - linkAccount

### ISSUE THREAD

**Issue by thepeterkovacs** [nextauthjs/next-auth#8283]
### Question 💬

While using the latest version of next-auth (4.22.5) and @auth/drizzle-adapter (0.2.1), the following error occurred in the NextAuthOptions:

  `Types of property 'linkAccount' are incompatible.`

I've set up the minimum required adapter in Postgres according to the documentation.

Here is my code:

```ts
import { DrizzleAdapter } from "@auth/drizzle-adapter"
import { SqlFlavorOptions } from "@auth/drizzle-adapter/lib/utils"
import { NextAuthOptions } from "next-auth"
import GithubProvider from "next-auth/providers/github"

import { db } from "@/database/supabase/connection"
import { pgTable } from "@/database/supabase/schema"

export const options: NextAuthOptions = {
        /* the error occurs here */
	adapter: DrizzleAdapter(db as SqlFlavorOptions, pgTable),
	providers: [
		GithubProvider({
			clientId: process.env.GITHUB_CLIENT_ID,
			clientSecret: process.env.GITHUB_CLIENT_SECRET,
		}),
...
```

Any idea how to resolve this issue?
Thanks in advance!

### How to reproduce ☕️

Follow the documentation for setting up the drizzle adapter with Postgres: https://authjs.dev/reference/adapter/drizzle#drizzleadapter

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by SSardorf** [comment]
I outline the issue here, if anyone wants to fix: https://github.com/nextauthjs/next-auth/issues/8280#issuecomment-1672940275

**Comment by balazsorban44** [comment]
I released a fix in `@auth/core`, which is a transient dependency of `@auth/*-adapter`. For it to take effect, you might need to delete `node_modules` and reinstall packages.

It's included in [@auth/core@0.10.4](https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fcore%400.10.4)

**Comment by SnekCode** [comment]
> I released a fix in `@auth/core`, which is a transient dependency of `@auth/*-adapter`. For it to take effect, you might need to delete `node_modules`/lock file and reinstall packages.
> 
> It's included in [@auth/core@0.10.4](https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fcore%400.10.4)
> 
> If that doesn't work, you can check your package manager's override config, eg. for pnpm adding the following to your `package.json` should fix the issue:
> 
> ```json
>   "pnpm": {
>     "overrides": {
>       "@auth/core": "^0.10.4"
>     }
>   }
> ```

Hello, I'm still experiencing this problem even after installing latest version of auth/core.  Attempted doing what you mentioned above with no luck

**Comment by balazsorban44** [comment]
If. you are importing types from `@auth/core/adapters`, make sure it's at least the above mentioned version. Otherwise you can keep using `next-auth/adapters` for your custom one.

**Comment by SnekCode** [comment]
Yup, was using `"@auth/core": "^0.11.1",`

I don't have an export from `next-auth/adapters` when using `"next-auth": "^4.23.0",`

**Comment by balazsorban44** [comment]
Fixed via https://github.com/nextauthjs/next-auth/commit/20c3fe3331273893651c68d2e43151b4ca0c67b4, will release later. 🙏

**Comment by 249Ayman** [comment]
for me the way I fixed it is it was my first time using authjs and drizzle and I just copied the schema file without adding my own connection string:
