### ISSUE TITLE
Mongo Atlas - MongoServerSelectionError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by chechenev** [nextauthjs/next-auth#833]
**Your question**

What am I missing using Mongo Atlas?

**What are you trying to do**
1. I'm trying to use Google auth
2. Whitelisted all IPs on Mongo atlas
3. Using env variable gives me: `[next-auth][error][adapter_connection_error] MongoServerSelectionError: getaddrinfo ENOTFOUND cluster0.bixqg.mongodb.net`
4. I tried to do everything from similar issue [https://github.com/nextauthjs/next-auth/issues/314](https://github.com/nextauthjs/next-auth/issues/314) with no success
5. I tried to deploy to `vercel` to run it not locally - the same result

**Feedback**
My code:
```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
    // Configure one or more authentication providers
    providers: [
        Providers.Google({
            clientId: process.env.GOOGLE_ID,
            clientSecret: process.env.GOOGLE_SECRET
        }),
    ],

    database: process.env.DATABASE_URL,
};

export default (req, res) => NextAuth(req, res, options)
```

The full error:
```
[next-auth][error][adapter_connection_error] MongoServerSelectionError: getaddrinfo ENOTFOUND cluster0.bixqg.mongodb.net
    at Timeout._onTimeout (/Users/maxim/WebstormProjects/tovarisch/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'MongoServerSelectionError',
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map { 'cluster0.bixqg.mongodb.net:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
} 

[next-auth][error][oauth_callback_handler_error] TypeError: Cannot destructure property `manager` of 'undefined' or 'null'.

```
- [x] Found documentation but was incomplete

**Comment by SelvinM** [comment]
I'm having the same problem, everything was working fine last week. I'm not sure why the connection stopped working all of the sudden.

**Comment by SelvinM** [comment]
The issue seems to be related to typeorm only  https://github.com/typeorm/typeorm/issues/7009#issue-735368002 . 
Until they fix it, adding this to you package.json should fix the issue.
`"resolutions": {
		"**/type-orm": "0.2.28"
}`

**Comment by SelvinM** [comment]
The issue seems to be related to typeorm only. Watch this https://github.com/typeorm/typeorm/issues/7009 .
Adding this to you package.json should fix the issue temporarily until they fix it.
"resolutions": { "**/type-orm": "0.2.28" }

**Comment by SelvinM** [comment]
The issue seems to be related to typeorm version 0.2.29 according to this https://github.com/typeorm/typeorm/issues/7009 .

Adding this to your package.json should fix the issue `"resolutions": {
		"typeorm": "0.2.28"
	}`

**Comment by BskSmoothie** [comment]
Having same issue and adding `"resolutions": { "typeorm": "0.2.28" }` to my package.json didnt fix my problem. Any other ideas how to fix it?

**Comment by unflawed** [comment]
TypeORM for MongoDB is still in an experimental stage. https://github.com/typeorm/typeorm#Installation

**Comment by BskSmoothie** [comment]
> > Having same issue and adding `"resolutions": { "typeorm": "0.2.28" }` to my package.json didnt fix my problem. Any other ideas how to fix it?
> 
> Fixed. If you get this, you need to install and import the `reflect-metadata` package.
> 
> 1. Install the npm package: `npm install typeorm --save`
> 2. You need to install reflect-metadata shim: `npm install reflect-metadata --save`
> 3. Import `reflect-metadata` somewhere in the global place of your app (for example in app.ts):
> 
> ```js
> // _app.ts or _app.js
> import "reflect-metadata";
> ...
> ```
> 
> Suggest making this clearer in the docs if possible.

Worked for me. Thanks! 👍

**Comment by iaincollins** [comment]
Thank you for the updates, linking to the outstanding issue and for a workaround (and confirming it works for you).

I'm going to keep an eye on the open issue with typeorm to see if we will should make a change to address or if it's an issue they plan to address upstream.

**Comment by jrista** [comment]
I just switched from mLab to Mongo Atlas, and started having the same problem. I found this thread, and switched from `"typeorm": "^0.2.29"` to `"typeorm": "0.2.28"` (note the LACK of a caret ^ in the version, to LOCK it to 0.2.28). That seems to have resolved the issue, and I am now able to connect to Mongo Atlas.

If I switch back to 0.2.29 or use any kind of semantic version auto-upgrade option (^ or ~ or .x) in the version, it uses the latest, and also has a problem. Locking the typeorm node module version to 0.2.28 seems to resolve the issue.

**Comment by jrista** [comment]
FWIW, before I changed the typeorm version down to 0.2.28, I did a bunch of testing elsewhere. All connection strings, mongodb:// and mongo+srv://, worked everywhere else I tested them. The `mongo` cli, Studio3T, Robo3T, using the node mongodb driver directly, etc.

**Comment by IRediTOTO** [comment]
Still error, I can't fix this...

**Comment by IRediTOTO** [comment]
Guys, did you fix it?  @jrista 
I am using this setup: 
`database:  'mongodb+srv://usn:pw@cluster-my-data.h215u.gcp.mongodb.net/myDB',` 
I'm sure this connect work because I am using next connect, now I want use next-auth....

**Comment by IRediTOTO** [comment]
fixed by this command `npm i typeorm@0.2.28`

**Comment by mapsam** [comment]
@unflawed your solution worked for me, thanks so much! ❤️

**Comment by rajat1saxena** [comment]
I had been struggling with this for last five hours or so. @BskSmoothie's solution solved it for me.

**Comment by Haple** [comment]
> I just switched from mLab to Mongo Atlas, and started having the same problem. I found this thread, and switched from `"typeorm": "^0.2.29"` to `"typeorm": "0.2.28"` (note the LACK of a caret ^ in the version, to LOCK it to 0.2.28). That seems to have resolved the issue, and I am now able to connect to Mongo Atlas.
> 
> If I switch back to 0.2.29 or use any kind of semantic version auto-upgrade option (^ or ~ or .x) in the version, it uses the latest, and also has a problem. Locking the typeorm node module version to 0.2.28 seems to resolve the issue.

Solved for me! Thanks @jrista :)

**Comment by dextermb** [comment]
@iaincollins Could you pin this issue so it's easier for other `mongodb` users to find? Thanks! 🎉 

Adding the resolution to my `package.json` resolved the issue for me.

**Comment by jrista** [comment]
@IRediTOTO I fixed it by falling back to 0.2.28. The issue seems to be with 0.2.29.

**Comment by andrewgwallace** [comment]
> @IRediTOTO I fixed it by falling back to 0.2.28. The issue seems to be with 0.2.29.

What does your database connection object look like as well as URL? did you use npm or yarn?

**Comment by jrista** [comment]
@andrewgwallace I am currently using a mongo:// connection string.

**Comment by Furberg** [comment]
I got this as well while fooling around between two projects. The thing is that I only got it on one of them. The only difference was the connectionstring variable name in the `.env.local` file. Changing it from `DATABASE_URI` to `DATABASE_URL` (and updating all the references, rebuilding etc) made it work again. Not sure why, but worth a try.

**Comment by andrewgwallace** [comment]
> I got this as well while fooling around between two projects. The thing is that I only got it on one of them. The only difference was the connectionstring variable name in the `.env.local` file. Changing it from `DATABASE_URI` to `DATABASE_URL` (and updating all the references, rebuilding etc) made it work again. Not sure why, but worth a try.

YES! @Furberg's suggestion worked for me! Now, just need to resolve the SMTP issues...

**Comment by andrewgwallace** [comment]
OK -- With the help of the post from Furberg (who has mysteriously disappeared from the thread...maybe off to put in a PR for the fix?) I've narrowed the issue down to how the string is parsed by typeorm. To resolve this, you can construct the object yourself rather than pass a string. This way you don't have to install a previous typeorm version, modify your package.json, or include reflect-metadata. 

If your string looks like this:
`mongodb+srv://**<username>**:**<password>**@**<cluster>**.yu5ue.mongodb.net/**<dbname>**?retryWrites=true&w=majority`

In your options for NextAuth, make your `database` value an object instead of a string. The structure should look as follows:

  ```
database: {
    type: "mongodb",
    database: "<database>",
    database_url: "mongodb+srv://:@**<cluster>**.yu5ue.mongodb.net",
    user: "**<username>**",
    pass: "**<password>**",
    w: "majority",
    synchronize: true,
    logger: "debug",
    useNewUrlParser: true,
    useUnifiedTopology: true,
    retryWrites: true,
  },
```
Obviously it is recommended to store values in .env.local.

**Comment by Furberg** [comment]
For whatever reason my comment got lost. Here it is again:

> I got this as well while fooling around between two projects. The thing is that I only got it on one of them. The only difference was the connectionstring variable name in the `.env.local` file. Changing it from `DATABASE_URI` to `DATABASE_URL` (and updating all the references, rebuilding etc) made it work again. Not sure why, but worth a try.

**Comment by Furberg** [comment]
> To resolve for now without any "hackery", simply bypass the string parser's reliance on typeorm in the adapter and construct the object yourself. This way you don't have to install a previous typeorm version, modify your package.json, or include reflect-metadata.
> 
> If your string looks like this:
> `mongodb+srv://<username>:<password>@<cluster>.yu5ue.mongodb.net/<dbname>?retryWrites=true&w=majority`
> 
> In your options for NextAuth, make your `database` value an object instead of a string. The structure should look as follows:
> 
> ```
> ...
> database: {
>   type: "mongodb",
>   uri: "mongodb+srv://<username>:<password>@<cluster>.yu5ue.mongodb.net/<dbname>",
>   w: "majority",
>   useNewUrlParser: true,
>   useUnifiedTopology: true,
>   retryWrites: true,
> },
> ```
> 
> **Important**: Note that it says **uri** and not **url**.
> Obviously it is recommended to store values in .env.local.
> 
> Optional values such as `synchronize` and `logger` can also be added to the object.
> 
> Source of the issue seems to be coming from typeorm config.
> Big thanks to [Richard Furberg](https://github.com/Furberg) for pointing me in the right direction.

Worth mentioning is that I couldn't get the email configuration to work, until I changed it from a string to an object, just as you said about the connection string.

**Comment by jrista** [comment]
@andrewgwallace Thank you for the update. Sounds like its due to parsing a full string url down into the various connection config parts then...

For my purposes, I don't actually need mongodb+srv. Not at this stage of the project, anyway. So falling back to a mongodb:// url worked ok for me. Good to know that I can use an object for config though.

**Comment by AnxiousDarkly** [comment]
not sure if I am the only one, but I haven't been able to get it working with any method in this thread so far.

**Comment by huksley** [comment]
I have same problems and solution suggested by @andrewgwallace does not work for me :(

**Comment by unflawed** [comment]
@huksley have you tried this?
https://github.com/nextauthjs/next-auth/issues/833#issuecomment-723101500

**Comment by huksley** [comment]
@unflawed Yes, downgrading to `typeorm` `0.2.28` and following steps as  you suggested https://github.com/nextauthjs/next-auth/issues/833#issuecomment-723101500  fixed problem connecting to MongoDB, thanks 👍

**Comment by AnxiousDarkly** [comment]
sorry I was wrong, setting a resolutions for `typeorm` was the only suggestion that worked.

**Comment by andrewgwallace** [comment]
Yea -- my solution stopped working for me as well. 😭
I reverted to downgrading to typeorm 0.2.28 and the resolutions in my package.json. However now I'm getting 
`UnhandledPromiseRejectionWarning: Error: no optional dependency [mongodb] defined in peerOptionalDependencies in any package.json`
I've also installed mongodb as an optional dependency.

**Comment by SelvinM** [comment]
@andrewgwallace try changing "optionalDependencies" to "peerOptionalDependencies" in your package.json like so:
`"peerOptionalDependencies": {
		"mongodb": "^3.6.2"
	}`

**Comment by andrewgwallace** [comment]
> @andrewgwallace try changing "optionalDependencies" to "peerOptionalDependencies" in your package.json like so:
> `"peerOptionalDependencies": { "mongodb": "^3.6.2" }`

Yes that seems to have resolved it! Thank you @SelvinM !

**Comment by chechenev** [comment]
I was able to fix it using the following config in `[...nextauth].js`:
```
 database: {
        type: "mongodb",
        useNewUrlParser: true,
        url: process.env.DATABASE_URL,
        ssl: true,
        useUnifiedTopology: true,
        authSource: "admin",
    },
```

**Comment by Diaa-Ghonim** [comment]
fixed thanks a lot .

**Comment by imgregduh** [comment]
This worked for me 

```
// [...nextauth].js
database: process.env.DATABASE_URL,
```

```
// .env.local
DATABASE_URL=mongodb+srv://<user>:<password>@<cluster>.mongodb.net/<db>
```

`npm i typeorm@0.2.28`

**Comment by Zertz** [comment]
Although it hasn't been released yet, the [PR](https://github.com/typeorm/typeorm/pull/7136) to fix this in TypeORM has been merged.

**Comment by matiastucci** [comment]
Any new ideas? I tried all the suggestions but I still get the same error.

**Comment by matiastucci** [comment]
This worked for me:

`yarn add typeorm@next`

and adding this in the `package.json`:

```json
"resolutions": {
  "typeorm": "0.3.0-alpha.24"
},
```

**Comment by YuriGor** [comment]
similar to @matiastucci 's solution. this one works for me with npm + npm-force-resolutions

**Comment by iaincollins** [comment]
@Zertz @matiastucci Thanks for the update!

Great to know there is a fix in progress with TypeORM!

Will get that rolled in and we can update the dependencies and docs when typeorm@0.3.0 is out.

**Comment by pleerock** [comment]
Fix should be available in the latest `typeorm` @0.2.30

**Comment by timsoraro** [comment]
I still have the same problem ):

`[...nextauth].js`
```
database: {
    type: "mongodb",
    uri: process.env.MONGO_URI,
    w: "majority",
    useNewUrlParser: true,
    useUnifiedTopology: true,
    retryWrites: true,
  },
```

`.env`
```
MONGO_URI=mongodb+srv://admin-name:Pass@cluster0.ya3ss.mongodb.net/DB
```

`package.json`
```
{
  "name": "nextauth-examples",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "mongodb": "^3.6.3",
    "mongoose": "^5.11.11",
    "next": "10.0.1",
    "next-auth": "^3.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
  }
}
```

**Comment by balazsorban44** [comment]
this is available in the latest canary release!

**Comment by jrista** [comment]
We just updated to 0.2.31, then tried 0.2.30 as well...and we seem to have lost the ability to connect to an ObjectRocket Mongo DB with a normal mongo:// connection string. We connected to a local mongo fine, but the ObjectRocket is the service we use in all of our non-local environments. Not real sure what the issue is...it just seems to time out trying to connect.

**Comment by payzly-dev** [comment]
1. `npm i typeorm@0.2.28`
2. Remove carrot from the type orm version in your package.json file so that it looks like this:  `"typeorm": "0.2.28"`
3. Ensure you have the following in your package.json file:
```
"peerOptionalDependencies": {
    "mongodb": "^3.6.3"
  },
```
