### ISSUE TITLE
How to declare module "next-auth/jwt" in next-auth@5

### ISSUE THREAD

**Issue by Adherentman** [nextauthjs/next-auth#9645]
### What is the improvement or update you wish to see?

<img width="907" alt="image" src="https://github.com/nextauthjs/next-auth/assets/26477346/38db1e61-d93e-476d-887e-065414891e21">

### Is there any context that might help us understand?

I want Module Augmentation jwt type. but get this error

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/typescript

**Comment by balazsorban44** [comment]
should be fixed in #9617 and released in beta.5. please upgrade and test it out

**Comment by Talent30** [comment]
Hi, @balazsorban44. Still having the same issue in beta.5
https://stackblitz.com/edit/stackblitz-starters-cz8es6?file=package.json,auth.config.ts,package-lock.json

**Comment by Adherentman** [comment]
> Hi, @balazsorban44. Still having the same issue in beta.5 https://stackblitz.com/edit/stackblitz-starters-cz8es6?file=package.json,auth.config.ts,package-lock.json

mee too

**Comment by Aw3same** [comment]
What work for me was: 

```typescript
declare module '@auth/core/types' {
	interface User extends LSUser {}

	interface Session {
		user: Pick<
			LSUser,
			| 'id'			
			| 'firstName'
			| 'lastName'
		> & {
			permissions: string[]
		}
	}
}

declare module '@auth/core/jwt' {
	interface JWT {
		accessToken: string
		expiresAt: number
		refreshToken: string
		error?: 'RefreshAccessTokenError'
	}
}
```

**Comment by Adherentman** [comment]
@Aw3same What is your next-auth version?

**Comment by Aw3same** [comment]
`beta.4` ,but it still working on `beta.5`

**Comment by tresorama** [comment]
I don't know if it is expected but this works for me too:
```ts
// in auth.d.ts

declare module "@auth/core/jwt" {
  interface JWT_Custom {
    account?: Account,
    profile?: Profile,
    user?: UserFromDB_Safe,
  }
  interface JWT extends JWT_Custom { }
}

declare module "next-auth" {
  interface Session {
    token: JWT;
  }
}
```

**Comment by ev0clu** [comment]
Still the same error with 5.0.0-beta.22.

> Invalid module name in augmentation, module 'next-auth/jwt' cannot be found.

```
declare module "next-auth/jwt" {
  interface JWT {
    accessToken?: string
  }
}
```
