### ISSUE TITLE
Session callback Type error: Property 'user' does not exist on type 

### ISSUE THREAD

**Issue by ochoadan** [nextauthjs/next-auth#9802]
### Environment

{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.1.0",
    "next-auth": "^5.0.0-beta.5",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}

### Reproduction URL

https://github.com/ochoadan/base-next-nextauth-error

### Describe the issue

Property 'user' does not exist on type '({ session: Session; user: AdapterUser; } | { session: Session; token: JWT; }) & { newSession: any; trigger?: "update" | undefined; }'.ts(2339)
Happens with user and token:
![image](https://github.com/nextauthjs/next-auth/assets/42155753/73376d0a-9ee8-4e68-802e-5b991b3f7888)

### How to reproduce

The issue comes from a raw application, I don't know where it comes from.

### Expected behavior

No typescript errors

**Comment by balazsorban44** [comment]
Already fixed in #9756, will be released soon

**Comment by Aw3same** [comment]
I'm still having this error on `beta.5`: 
![image](https://github.com/nextauthjs/next-auth/assets/10500082/690e4357-d19a-4fae-a852-f5c5259422d6)

my versions are: 
```
    "@auth/prisma-adapter": "^1.1.0",
    "@prisma/client": "^5.8.1",
    "next": "^14.1.0",
    "next-auth": "^5.0.0-beta.5",
    "react": "^18",
    "react-dom": "^18",
    "typescript": "^5"
```

I saw my folder `@auth` in `node_modules` to see the version of the `@auth/core`, and it's 
![image](https://github.com/nextauthjs/next-auth/assets/10500082/07c39578-0da9-42fd-8f8a-efb2ee705d77)

If i downgrade to `beta.4` it works fine
